# Generated by Django 6.0.4 on 2026-05-19 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0031_formulation_formulations_org_sales_idx'),
        ('organizations', '0012_mrpeasy_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WixFormSchemaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wix_form_id', models.UUIDField()),
                ('wix_namespace', models.CharField(max_length=64)),
                ('field_labels', models.JSONField(help_text='Mapping {field_key: human_label}. Looked up by the UI every time a submission is rendered, so keep it flat.')),
                ('raw_schema', models.JSONField(help_text='Full schema response — kept for debugging only.')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wix form schema cache',
                'verbose_name_plural': 'Wix form schema caches',
                'constraints': [models.UniqueConstraint(fields=('wix_form_id', 'wix_namespace'), name='cff_wix_form_schema_unique')],
            },
        ),
        migrations.CreateModel(
            name='CFFSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wix_submission_id', models.UUIDField(help_text="Wix's id for the submission. Idempotency key.", unique=True)),
                ('wix_form_id', models.UUIDField(db_index=True)),
                ('wix_namespace', models.CharField(default='wix.form_app.form', max_length=64)),
                ('wix_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('PAYMENT_REQUIRED', 'Payment required'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_CANCELED', 'Payment canceled'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32)),
                ('wix_created_date', models.DateTimeField()),
                ('wix_updated_date', models.DateTimeField()),
                ('raw_payload', models.JSONField(help_text='Full submission object from Wix. Rendered field-by-field in the UI; never re-shape into columns or we lose the ability to handle form-schema drift.')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Stamped on every successful re-pull from Wix.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who attached this CFF to its project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Org that owns this CFF intake stream. Populated at import time from settings.WIX_CFF_TARGET_ORGANIZATION_ID.', on_delete=django.db.models.deletion.PROTECT, related_name='cff_submissions', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project this CFF was assigned to. Null = unassigned, which is the headline state surfaced by the UI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cff_submissions', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'CFF submission',
                'verbose_name_plural': 'CFF submissions',
                'ordering': ('-wix_created_date',),
                'indexes': [models.Index(fields=['organization', 'project'], name='cff_submiss_organiz_d44e84_idx'), models.Index(fields=['organization', '-wix_created_date'], name='cff_submiss_organiz_f2cb54_idx'), models.Index(fields=['organization', '-wix_updated_date'], name='cff_submiss_organiz_16513f_idx')],
            },
        ),
    ]
