# Generated by Django 6.0.4 on 2026-05-21 11:06

from django.db import migrations, models


def _backfill_submitter_email(apps, schema_editor):
    """Populate ``submitter_email`` on every existing row by walking
    its ``raw_payload.submissions`` dict for an ``email_*`` slug.

    Inlined (rather than importing from the services module) so the
    data migration stays stable against future refactors to the
    extractor — historic state should backfill against the rule
    that applied when this migration ran, not whatever the
    extractor returns six months from now.
    """

    Submission = apps.get_model("cff_submissions", "CFFSubmission")

    # Mirror the live ``SUBMITTER_EMAIL_SLUG_PREFIXES`` /
    # ``SALES_PERSON_EMAIL_SLUG_PREFIXES`` lists so the backfill
    # matches what the importer would write today.
    SALES_PREFIXES = (
        "vita_manufacture_account_manager_email",
        "account_manager_email",
    )
    EMAIL_PREFIXES = ("email_address", "email")

    def extract(raw_payload):
        submissions = (
            raw_payload.get("submissions")
            if isinstance(raw_payload, dict)
            else None
        )
        if not isinstance(submissions, dict):
            return ""
        for slug, value in submissions.items():
            if any(slug.startswith(p) for p in SALES_PREFIXES):
                continue
            if not any(slug.startswith(p) for p in EMAIL_PREFIXES):
                continue
            if isinstance(value, str) and value.strip():
                return value.strip()[:320]
        return ""

    # Iterate the existing rows in batches so we never hold the
    # entire table in memory on a tenant that has years of intake
    # already accumulated.
    qs = Submission.objects.filter(submitter_email="").only(
        "id", "raw_payload", "submitter_email",
    )
    batch: list = []
    BATCH_SIZE = 500
    for sub in qs.iterator(chunk_size=BATCH_SIZE):
        email = extract(sub.raw_payload)
        if not email:
            continue
        sub.submitter_email = email
        batch.append(sub)
        if len(batch) >= BATCH_SIZE:
            Submission.objects.bulk_update(batch, ["submitter_email"])
            batch = []
    if batch:
        Submission.objects.bulk_update(batch, ["submitter_email"])


def _noop_reverse(apps, schema_editor):
    """The column is being dropped on reverse — no data needs to
    survive the trip back."""


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cffsubmission',
            name='submitter_email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Customer-typed email harvested from raw_payload at import time. Empty when the form has no email slug.', max_length=320),
        ),
        migrations.RunPython(
            _backfill_submitter_email,
            _noop_reverse,
        ),
    ]
