# Generated by Django 6.0.4 on 2026-07-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0003_cff_project_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cffsubmission',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set the moment a triage user marks the CFF as rejected. NULL means the CFF is either in triage or already assigned.', null=True),
        ),
        migrations.AddField(
            model_name='cffsubmission',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text="The triage user who rejected the CFF. Nulled on unreject so subsequent re-rejections don't stack conflicting authorship.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_cff_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cffsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text="Free-text reason shown alongside the row in the rejected list. Empty when the CFF isn't rejected."),
        ),
    ]
