# Generated by Django 6.0.4 on 2026-07-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0004_cffsubmission_rejected_at_cffsubmission_rejected_by_and_more'),
        ('client_portal', '0006_self_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cffsubmission',
            name='provenance',
            field=models.CharField(choices=[('wix', 'Wix marketing form'), ('portal', 'Portal (authenticated)')], db_index=True, default='wix', help_text='Where the submission originated. Wix rows come from the public marketing form via the poller; portal rows come from the authenticated customer portal.', max_length=16, verbose_name='provenance'),
        ),
        migrations.AddField(
            model_name='cffsubmission',
            name='submitted_by_client_account',
            field=models.ForeignKey(blank=True, help_text='Portal customer that authored this submission. NULL when the CFF came in via Wix (anonymous marketing form).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cffs', to='client_portal.clientaccount'),
        ),
        migrations.AlterField(
            model_name='cffsubmission',
            name='raw_payload',
            field=models.JSONField(help_text='Full form response object. For Wix rows this is the raw Wix API payload; for portal rows we build the same slug-keyed ``submissions`` shape so triage renders both uniformly. Never re-shape into columns or we lose resilience against form-schema drift.'),
        ),
        migrations.AlterField(
            model_name='cffsubmission',
            name='wix_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cffsubmission',
            name='wix_form_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cffsubmission',
            name='wix_submission_id',
            field=models.UUIDField(blank=True, help_text="Wix's id for the submission. Idempotency key. NULL for portal rows.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cffsubmission',
            name='wix_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
