# Generated by Django 6.0.4 on 2026-07-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0005_cffsubmission_provenance_and_more'),
        ('proposals', '0018_proposal_deposit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cffsubmission',
            name='drafted_proposal',
            field=models.ForeignKey(blank=True, help_text='Auto-drafted proposal for RTG submissions. Triage opens this proposal, sanity-checks the lines, and hits Send — no re-typing. NULL on Custom rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rtg_cff_submissions', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='cffsubmission',
            name='submission_kind',
            field=models.CharField(choices=[('custom', 'Custom brief'), ('ready_to_go', 'Ready-to-Go order')], db_index=True, default='custom', help_text="Discriminates a bespoke Custom brief from a Ready-to-Go order off the published catalog. Drives the triage-inbox badge and, on the customer portal, whether the pending card reads 'Under review' or 'Awaiting proposal'.", max_length=16, verbose_name='submission kind'),
        ),
    ]
