# Generated by Django 6.0.4 on 2026-07-30 07:05

from django.db import migrations, models


def _extract_name(raw_payload):
    """Duplicated inline (not imported from services.py) because data
    migrations must not depend on runtime app code — a future refactor
    that renames the helper would silently break the historical
    migration run on a fresh clone. Kept in lock-step with
    ``services.extract_submitter_name``.
    """

    if not isinstance(raw_payload, dict):
        return ""
    submissions = raw_payload.get("submissions")
    if not isinstance(submissions, dict):
        return ""
    first_name = ""
    last_name = ""
    for slug, value in submissions.items():
        if not isinstance(value, str) or not value.strip():
            continue
        lowered = slug.lower()
        if not first_name and lowered.startswith("first_name"):
            first_name = value.strip()
        elif not last_name and lowered.startswith("last_name"):
            last_name = value.strip()
        if first_name and last_name:
            break
    return " ".join(part for part in (first_name, last_name) if part)[:300]


def _backfill_submitter_name(apps, schema_editor):
    """Populate the denormalised ``submitter_name`` column for every
    pre-existing row.

    Chunked to keep memory bounded on tenants with years of intake
    already accumulated. Mirrors the shape of migration 0002's
    email backfill so the two evolutions read identically.
    """

    Submission = apps.get_model("cff_submissions", "CFFSubmission")
    qs = Submission.objects.filter(submitter_name="").only(
        "id", "raw_payload", "submitter_name",
    )
    batch: list = []
    BATCH_SIZE = 500
    for sub in qs.iterator(chunk_size=BATCH_SIZE):
        name = _extract_name(sub.raw_payload)
        if not name:
            continue
        sub.submitter_name = name
        batch.append(sub)
        if len(batch) >= BATCH_SIZE:
            Submission.objects.bulk_update(batch, ["submitter_name"])
            batch = []
    if batch:
        Submission.objects.bulk_update(batch, ["submitter_name"])


def _noop_reverse(apps, schema_editor):
    """The column is being dropped on reverse — no data needs to
    survive the trip back."""


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0006_cffsubmission_submission_kind_drafted_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cffsubmission',
            name='submitter_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='First + last name harvested from raw_payload at import time. Feeds the CFF search picker; the payload is the source of truth, this column is a cheap lookup.', max_length=300),
        ),
        migrations.RunPython(_backfill_submitter_name, _noop_reverse),
    ]
