# Generated by Django 6.0.4 on 2026-07-30 07:23

from django.conf import settings
from django.db import migrations, models


def _dedupe_assignments(apps, schema_editor):
    """Enforce one CFF per project on any tenant that pre-dates the
    constraint by deleting older assignment rows on projects that
    currently carry multiple.

    Keeps the *most-recently-assigned* row — matches operator intent
    that the newest link is the correct one. Runs before
    ``AddConstraint`` so the constraint creation itself never fails.
    """

    Assignment = apps.get_model("cff_submissions", "CFFProjectAssignment")
    project_ids = (
        Assignment.objects.values("project_id")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
        .values_list("project_id", flat=True)
    )
    for project_id in list(project_ids):
        # For each conflicting project, keep the newest assignment
        # and delete the rest.
        keeper_id = (
            Assignment.objects.filter(project_id=project_id)
            .order_by("-assigned_at")
            .values_list("id", flat=True)
            .first()
        )
        Assignment.objects.filter(project_id=project_id).exclude(
            id=keeper_id
        ).delete()


def _noop_reverse(apps, schema_editor):
    """The dedupe on forward is destructive but the reverse is
    intentionally a no-op — we can't reconstruct the assignment rows
    we dropped, and the reverse just drops the constraint anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0007_cffsubmission_submitter_name'),
        ('formulations', '0064_formulationversion_snapshot_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedupe_assignments, _noop_reverse),
        migrations.AddConstraint(
            model_name='cffprojectassignment',
            constraint=models.UniqueConstraint(fields=('project',), name='cff_assignment_unique_per_project'),
        ),
    ]
