# Generated by Django 6.0.4 on 2026-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0008_one_cff_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cffsubmission',
            name='submission_kind',
            field=models.CharField(choices=[('custom', 'Custom brief'), ('ready_to_go', 'Ready-to-Go order'), ('reorder', 'Reorder of past Custom')], db_index=True, default='custom', help_text="Discriminates a bespoke Custom brief from a Ready-to-Go order off the published catalog. Drives the triage-inbox badge and, on the customer portal, whether the pending card reads 'Under review' or 'Awaiting proposal'.", max_length=16, verbose_name='submission kind'),
        ),
    ]
