# Generated by Django 6.0.4 on 2026-05-15 07:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text="Hex-encoded SHA-256 of the plaintext token that was emailed to the user. Stored hashed so a DB dump can't be turned into working reset links.", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a fresher reset request superseded this token before the user clicked through. Distinct from used_at.', null=True)),
                ('requested_ip', models.CharField(blank=True, default='', help_text='Audit breadcrumb — IPv4/IPv6 of the requester.', max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_13d348_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx')],
            },
        ),
    ]
