# Generated by Django 6.0.4 on 2026-05-27 11:17

import apps.label_design.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0005_portalevent'),
        ('formulations', '0033_formulation_formulations_org_lead_sci_idx'),
        ('organizations', '0014_backfill_proposals_view_all'),
        ('specifications', '0016_specificationsheet_specs_fv_kind_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDesignPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_names', models.TextField(blank=True, default='')),
                ('product_codes', models.TextField(blank=True, default='')),
                ('brand_colours', models.JSONField(blank=True, default=list, help_text='List of ``{ "name": "...", "hex": "#..." }`` entries.', verbose_name='brand colours')),
                ('inspiration_urls', models.JSONField(blank=True, default=list, help_text='List of URL strings the customer referenced as visual inspiration.', verbose_name='inspiration URLs')),
                ('elements_to_include', models.TextField(blank=True, default='', verbose_name='specific elements to include')),
                ('design_style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('minimalist', 'Minimalist'), ('bold', 'Bold'), ('luxury', 'Luxury')], default='', max_length=16, verbose_name='design style')),
                ('material_type', models.CharField(blank=True, choices=[('matte', 'Matte'), ('glossy', 'Glossy')], default='', max_length=16, verbose_name='material type')),
                ('additional_comments', models.TextField(blank=True, default='', verbose_name='additional comments')),
                ('declaration_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='declaration signed at')),
                ('declaration_signature_image', models.TextField(blank=True, default='', verbose_name='declaration signature image')),
                ('declaration_name', models.CharField(blank=True, default='', max_length=200)),
                ('declaration_position', models.CharField(blank=True, default='', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('submitted_by_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_label_preferences', to='client_portal.clientaccount')),
            ],
            options={
                'verbose_name': 'label design preferences',
                'verbose_name_plural': 'label design preferences',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='LabelDesignPreferenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.label_design.models._preference_file_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_files', to='label_design.labeldesignpreferences')),
            ],
            options={
                'verbose_name': 'label design inspiration file',
                'verbose_name_plural': 'label design inspiration files',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='LabelDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], db_index=True, default='payment_pending', max_length=32, verbose_name='status')),
                ('design_path', models.CharField(blank=True, choices=[('design_by_us', 'Vita designs'), ('design_by_customer', 'Customer designs')], default='', help_text='Which side does the artistic work. Blank until the customer picks on the portal.', max_length=24, verbose_name='design path')),
                ('rejection_count', models.PositiveSmallIntegerField(default=0, help_text='Bumped each time the customer rejects on the CUSTOMER_APPROVAL step; reset when the next customer approval lands. The transition service auto-routes to ``ON_HOLD`` once this exceeds ``MAX_CUSTOMER_REJECTIONS_BEFORE_HOLD``.', verbose_name='consecutive customer rejections')),
                ('customer_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='customer approved at')),
                ('customer_approval_signature_image', models.TextField(blank=True, default='', help_text='Base64-encoded PNG data URL captured on the portal signature pad.', verbose_name='customer approval signature image')),
                ('customer_sign_ip', models.CharField(blank=True, default='', max_length=45, verbose_name='customer sign ip')),
                ('customer_sign_user_agent', models.TextField(blank=True, default='', verbose_name='customer sign user agent')),
                ('customer_sign_document_hash', models.CharField(blank=True, default='', help_text='SHA-256 hex digest of the rendered approval HTML the customer saw at sign time. ESIGN drift detector.', max_length=64, verbose_name='customer sign document hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_label_designs', to=settings.AUTH_USER_MODEL)),
                ('customer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_label_designs', to='client_portal.clientaccount')),
                ('formulation', models.OneToOneField(help_text='The project this label belongs to. One label-design workflow per project — re-runs of the label phase live in the revision history.', on_delete=django.db.models.deletion.CASCADE, related_name='label_design', to='formulations.formulation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_designs', to='organizations.organization')),
                ('specification_sheet', models.ForeignKey(blank=True, help_text='The customer-signed final spec sheet whose acceptance gated entry to this workflow. PROTECT because a spec that was the basis of a label cannot be silently deleted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_designs', to='specifications.specificationsheet')),
                ('preferences', models.OneToOneField(blank=True, help_text='MA-ST-B-009 form payload. Only populated on the DESIGN_BY_US path.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_design_link', to='label_design.labeldesignpreferences')),
            ],
            options={
                'verbose_name': 'label design',
                'verbose_name_plural': 'label designs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LabelDesignRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(help_text='Monotonic per label_design; assigned by the service layer at submit time. Numbering starts at 1.', verbose_name='revision number')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', models.CharField(choices=[('staff_upload', 'Staff upload'), ('customer_upload', 'Customer upload')], max_length=24, verbose_name='source')),
                ('artwork_pdf', models.FileField(blank=True, help_text='Canonical archived artwork file. Stored on the Azure container in production, on the local filesystem in dev.', null=True, upload_to=apps.label_design.models._revision_artwork_upload_to, verbose_name='artwork PDF')),
                ('artwork_preview_png', models.FileField(blank=True, help_text='Auto-generated thumbnail rendered from the artwork PDF for the list / workspace surfaces.', null=True, upload_to=apps.label_design.models._revision_preview_upload_to, verbose_name='preview PNG')),
                ('compliance_block_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen content-block dict at submit time. Lets reviewers compare what was required vs what was delivered, and survives later spec edits — see plan §Spec drift risk.', verbose_name='compliance block snapshot')),
                ('customer_approved_own_design', models.BooleanField(default=False, help_text='True when the customer self-designed and uploaded the artwork; the explicit CUSTOMER_APPROVAL step is skipped because this acts as their approval.', verbose_name='customer approved own design')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('label_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='label_design.labeldesign')),
                ('submitted_by_client', models.ForeignKey(blank=True, help_text='Portal customer who submitted this revision. Null when a staff designer submitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_label_revisions', to='client_portal.clientaccount')),
                ('submitted_by_user', models.ForeignKey(blank=True, help_text='Staff designer who submitted this revision. Null when the customer self-designed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_label_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label design revision',
                'verbose_name_plural': 'label design revisions',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='LabelDesignReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scientist', 'Scientist'), ('director', 'Director')], max_length=16, verbose_name='kind')),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('requires_revision', 'Requires revisions')], max_length=24, verbose_name='outcome')),
                ('checklist_responses', models.JSONField(default=list, help_text='List of ``{item_key, pass, comment}``. Validated by the review serializer against ``constants.COMPLIANCE_CHECKLIST_KEYS`` — every checklist item must be present, no extras allowed.', verbose_name='checklist responses')),
                ('final_comments', models.TextField(help_text='Mandatory — the regulatory team requires reviewers to describe exactly what they reviewed. Enforced at the serializer + service layer.', verbose_name='final comments')),
                ('signature_image', models.TextField(blank=True, default='', help_text='Base64-encoded signature pad capture. Same shape as the prepared-by / director signatures on SpecificationSheet.', verbose_name='signature image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_reviews', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='label_design.labeldesignrevision')),
            ],
            options={
                'verbose_name': 'label design review',
                'verbose_name_plural': 'label design reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='labeldesign',
            name='current_revision',
            field=models.ForeignKey(blank=True, help_text='Denormalised pointer to the revision currently in review or approved. Avoids a subquery on the hot path.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='label_design.labeldesignrevision'),
        ),
        migrations.CreateModel(
            name='LabelDesignTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], default='', help_text='Status the workflow left. Blank when the row is created by the bootstrap signal (no prior status).', max_length=32, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], max_length=32, verbose_name='to status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form keys: revision_id / review_id / payment_id depending on which trigger fired the transition.', verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_design_transitions', to=settings.AUTH_USER_MODEL)),
                ('actor_client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_design_transitions', to='client_portal.clientaccount')),
                ('label_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='label_design.labeldesign')),
            ],
            options={
                'verbose_name': 'label design transition',
                'verbose_name_plural': 'label design transitions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='labeldesignrevision',
            index=models.Index(fields=['label_design', '-revision_number'], name='label_desig_label_d_b21768_idx'),
        ),
        migrations.AddConstraint(
            model_name='labeldesignrevision',
            constraint=models.UniqueConstraint(fields=('label_design', 'revision_number'), name='label_design_revision_unique_number'),
        ),
        migrations.AddIndex(
            model_name='labeldesignreview',
            index=models.Index(fields=['revision', 'kind'], name='label_desig_revisio_1a3267_idx'),
        ),
        migrations.AddConstraint(
            model_name='labeldesignreview',
            constraint=models.UniqueConstraint(fields=('revision', 'kind'), name='label_design_review_unique_per_revision_kind'),
        ),
        migrations.AddIndex(
            model_name='labeldesign',
            index=models.Index(fields=['organization', 'status'], name='label_desig_organiz_9e2a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='labeldesign',
            index=models.Index(fields=['organization', '-updated_at'], name='label_desig_organiz_417415_idx'),
        ),
        migrations.AddIndex(
            model_name='labeldesigntransition',
            index=models.Index(fields=['label_design', '-created_at'], name='label_desig_label_d_f87a67_idx'),
        ),
    ]
