# Generated by Django 6.0.4 on 2026-05-29 11:17

import apps.label_design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldesignpreferencefile',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.label_design.models._preference_file_upload_to),
        ),
        migrations.AlterField(
            model_name='labeldesignrevision',
            name='artwork_pdf',
            field=models.FileField(blank=True, help_text='Canonical archived artwork file. Stored on the Azure container in production, on the local filesystem in dev.', max_length=255, null=True, upload_to=apps.label_design.models._revision_artwork_upload_to, verbose_name='artwork PDF'),
        ),
        migrations.AlterField(
            model_name='labeldesignrevision',
            name='artwork_preview_png',
            field=models.FileField(blank=True, help_text='Auto-generated thumbnail rendered from the artwork PDF for the list / workspace surfaces.', max_length=255, null=True, upload_to=apps.label_design.models._revision_preview_upload_to, verbose_name='preview PNG'),
        ),
    ]
