# Generated by Django 6.0.4 on 2026-06-01 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0005_portalevent'),
        ('formulations', '0033_formulation_formulations_org_lead_sci_idx'),
        ('label_design', '0002_alter_labeldesignpreferencefile_file_and_more'),
        ('organizations', '0014_backfill_proposals_view_all'),
        ('specifications', '0016_specificationsheet_specs_fv_kind_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldesign',
            name='formulation',
            field=models.ForeignKey(help_text='The project this label belongs to. A project can carry MORE THAN ONE label-design row when it has multiple specs — each spec gets its own artwork workflow even though the project shares a single payment.', on_delete=django.db.models.deletion.CASCADE, related_name='label_designs', to='formulations.formulation'),
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='specification_sheet',
            field=models.ForeignKey(blank=True, help_text='The customer-signed final spec sheet whose acceptance gated entry to this workflow. PROTECT because a spec that was the basis of a label cannot be silently deleted. Pinned 1:1 with this label-design row via the partial UniqueConstraint in Meta so two specs in the same project always produce two distinct label workflows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_designs', to='specifications.specificationsheet'),
        ),
        migrations.AddIndex(
            model_name='labeldesign',
            index=models.Index(fields=['formulation'], name='label_desig_formula_af1cd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='labeldesign',
            constraint=models.UniqueConstraint(condition=models.Q(('specification_sheet__isnull', False)), fields=('formulation', 'specification_sheet'), name='label_design_unique_per_formulation_spec'),
        ),
    ]
