# Generated by Django 6.0.4 on 2026-06-01 10:23

import apps.label_design.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_design', '0003_alter_labeldesign_formulation_and_more'),
        ('organizations', '0014_backfill_proposals_view_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDesignTemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers render first. Lets staff curate the order without renaming categories.', verbose_name='sort order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_design_template_categories', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'label design template category',
                'verbose_name_plural': 'label design template categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LabelDesignTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('file', models.FileField(help_text='Any file type accepted (PDF, PNG, JPG, AI, PSD, ZIP, …). The Azure container the file lands in inherits the media-container ACL — public read; staff-managed write.', max_length=255, upload_to=apps.label_design.models._template_upload_to, verbose_name='file')),
                ('file_original_name', models.CharField(blank=True, default='', help_text="Customer-visible filename at upload time. Used to seed the Content-Disposition header on download so the file lands with a sensible name on the customer's disk.", max_length=255, verbose_name='original filename')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text="Captured at upload time; the FE renders it as KB / MB next to the download button so customers know what they're about to fetch.", verbose_name='file size (bytes)')),
                ('content_type', models.CharField(blank=True, default='', help_text='MIME type sniffed at upload time. Used to render an appropriate icon + as a hint for the download header.', max_length=120, verbose_name='content type')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_label_design_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_design_templates', to='organizations.organization')),
                ('category', models.ForeignKey(help_text='PROTECT because deleting a category that still has templates attached would silently break customer downloads — staff has to clear the category first.', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='label_design.labeldesigntemplatecategory')),
            ],
            options={
                'verbose_name': 'label design template',
                'verbose_name_plural': 'label design templates',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='labeldesigntemplatecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='label_design_template_category_unique_name'),
        ),
        migrations.AddIndex(
            model_name='labeldesigntemplate',
            index=models.Index(fields=['organization', 'category', 'sort_order'], name='label_desig_organiz_08c5cf_idx'),
        ),
    ]
