# Generated by Django 6.0.4 on 2026-08-25 09:53

import apps.label_design.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_design', '0005_collapse_label_designs_per_formulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldesign',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], db_index=True, default='payment_pending', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='labeldesigntransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], default='', help_text='Status the workflow left. Blank when the row is created by the bootstrap signal (no prior status).', max_length=32, verbose_name='from status'),
        ),
        migrations.AlterField(
            model_name='labeldesigntransition',
            name='to_status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('on_hold', 'On hold')], max_length=32, verbose_name='to status'),
        ),
        migrations.CreateModel(
            name='LabelDesignRevisionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=apps.label_design.models._revision_asset_upload_to, verbose_name='file')),
                ('label', models.CharField(blank=True, default='', max_length=80, verbose_name='view label')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='content type')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='size in bytes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_assets', to='label_design.labeldesignrevision')),
            ],
            options={
                'verbose_name': 'label design revision asset',
                'verbose_name_plural': 'label design revision assets',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['revision', 'sort_order'], name='label_desig_revisio_ee15e1_idx')],
            },
        ),
    ]
