# Generated by Django 6.0.4 on 2026-09-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0076_packagingcomboitem_stage'),
        ('label_design', '0007_labeldesign_per_proposal'),
        ('proposals', '0020_proposal_brand_key'),
        ('specifications', '0018_specificationsheet_customer_rejected_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labeldesign',
            new_name='label_desig_proposa_390389_idx',
            old_name='label_desig_proposa_ee8f4b_idx',
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='design_path',
            field=models.CharField(blank=True, choices=[('design_by_us', 'Vita designs'), ('design_by_customer', 'Customer designs'), ('no_label', 'No label required')], default='', help_text='Which side does the artistic work. Blank until the customer picks on the portal.', max_length=24, verbose_name='design path'),
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='formulation',
            field=models.ForeignKey(help_text="The formulation (product) this label workflow covers. One LabelDesign per (formulation, proposal) pair — Custom projects have one proposal today so this stays 1:1 per formulation; RTG catalog products get ordered N times and each order's proposal spawns its own label workflow so revisions + approvals stay scoped to the order the customer is looking at.", on_delete=django.db.models.deletion.CASCADE, related_name='label_designs', to='formulations.formulation'),
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text="The proposal / customer order this label belongs to. Nullable for legacy rows created before the per-proposal split; new rows always populate. Combined with ``formulation`` as the uniqueness key so a customer placing a second RTG order on the same catalog product gets a fresh label workflow instead of reusing the first order's.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_designs', to='proposals.proposal'),
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='specification_sheet',
            field=models.ForeignKey(blank=True, help_text="The customer-signed final spec sheet whose acceptance gated entry to this workflow. Kept for audit — points at the spec whose signature originally triggered the bootstrap. SET_NULL on delete because losing the spec row shouldn't cascade into losing the label workflow that followed from it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_designs', to='specifications.specificationsheet'),
        ),
        migrations.AlterField(
            model_name='labeldesign',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('no_label_required', 'No label required'), ('on_hold', 'On hold')], db_index=True, default='payment_pending', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='labeldesigntransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('no_label_required', 'No label required'), ('on_hold', 'On hold')], default='', help_text='Status the workflow left. Blank when the row is created by the bootstrap signal (no prior status).', max_length=32, verbose_name='from status'),
        ),
        migrations.AlterField(
            model_name='labeldesigntransition',
            name='to_status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('label_path_pending', 'Awaiting design path'), ('design_fee_pending', 'Awaiting design fee'), ('design_preferences_pending', 'Awaiting design preferences'), ('design_in_progress', 'Design in progress'), ('scientist_review', 'Scientist review'), ('director_review', 'Director review'), ('customer_approval', 'Customer approval'), ('label_approved', 'Label approved'), ('no_label_required', 'No label required'), ('on_hold', 'On hold')], max_length=32, verbose_name='to status'),
        ),
    ]
