# Generated by Django 6.0.4 on 2026-04-15 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Machine identifier used in URLs and permission checks. Snake_case, never renamed after creation.', max_length=64, verbose_name='slug')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='System catalogues are seeded automatically and referenced from business logic by slug. They cannot be deleted.', verbose_name='is system')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'catalogue',
                'verbose_name_plural': 'catalogues',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('internal_code', models.CharField(blank=True, help_text='Short SKU or part number. Optional, unique per catalogue.', max_length=64, verbose_name='internal code')),
                ('unit', models.CharField(blank=True, help_text='Physical unit the price is quoted in (e.g. g, mL, capsule).', max_length=32, verbose_name='unit')),
                ('base_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='base price')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Dynamic attribute map keyed by AttributeDefinition.key. Validated against the active definitions for this catalogue on every write.', verbose_name='attributes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalogues.catalogue')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['organization', 'slug'], name='catalogues__organiz_f0ec05_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogue',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='catalogues_catalogue_unique_slug_per_org'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['catalogue', 'name'], name='catalogues__catalog_beeae9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['catalogue', 'is_archived'], name='catalogues__catalog_815d15_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code', ''), _negated=True), fields=('catalogue', 'internal_code'), name='catalogues_item_unique_internal_code_per_catalogue'),
        ),
    ]
