# Generated by Django 6.0.4 on 2026-05-12 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['catalogue', 'is_archived', 'name'], name='catalogues_item_list_idx'),
        ),
    ]
