# Generated by Django 6.0.4 on 2026-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='psp_source_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='PSP source UUID'),
        ),
    ]
