# Generated by Django 6.0.4 on 2026-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_item_psp_source_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='regulatory_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', help_text='Compliance-risk tier for this ingredient. Rolled up on the project overview to flag products carrying a novel-food / restricted-market / high-allergen ingredient. Worst tier across bundled lines drives the product-level risk chip.', max_length=8, verbose_name='regulatory risk'),
        ),
    ]
