# Generated by Django 6.0.4 on 2026-05-20 09:16

import apps.client_portal.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_dynamics_id_customer_dynamics_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Login identity. Set from the Customer.email on the proposal that issued the activation token, so the address the kiosk email reached is the address that logs in. Never edited by the client themselves.', max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this account can sign in. Staff may flip this OFF to revoke portal access without deleting historical comments / signatures.', verbose_name='active')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Set once on the first successful activation (when the client sets their password via the kiosk-token landing page). ``NULL`` means the account row exists (we pre-create on send) but no one has set a password yet.', null=True, verbose_name='activated at')),
                ('last_login_ip', models.CharField(blank=True, default='', help_text='Most recent IP that completed a successful login. IPv4 or IPv6. Audit breadcrumb only — never gated on.', max_length=45)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The CRM row this account belongs to. PROTECT because deleting a Customer that still has live portal logins would orphan sessions; the staff side has to detach logins (or move them) first.', on_delete=django.db.models.deletion.PROTECT, related_name='client_accounts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'client account',
                'verbose_name_plural': 'client accounts',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.client_portal.managers.ClientAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text="Hex-encoded SHA-256 of the plaintext token emailed to the client. DB dump can't be turned into working reset links.", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a fresher request superseded this token. Distinct from ``used_at`` so the audit trail can tell a never-used token apart from a consumed one.', null=True)),
                ('requested_ip', models.CharField(blank=True, default='', max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='client_portal.clientaccount')),
            ],
            options={
                'verbose_name': 'client password reset token',
                'verbose_name_plural': 'client password reset tokens',
            },
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['email'], name='client_port_email_8cc904_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['customer'], name='client_port_custome_95e004_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpasswordresettoken',
            index=models.Index(fields=['account', '-created_at'], name='client_port_account_e28945_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpasswordresettoken',
            index=models.Index(fields=['expires_at'], name='client_port_expires_f5f9a8_idx'),
        ),
    ]
