# Generated by Django 6.0.4 on 2026-05-20 12:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(help_text='Address the customer typed into the settings form. Stored lowercased + trimmed so the confirm step can match against ``normalize_email`` output without needing a second normalisation pass.', max_length=254)),
                ('code_hash', models.CharField(help_text="SHA-256 of the plaintext 6-digit code sent in the verification email. Stored hashed so a DB dump can't be turned into a working email-change confirmation.", max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a fresher request superseded this one. Distinct from ``used_at`` so the audit log can tell an abandoned request apart from a consumed one.', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to='client_portal.clientaccount')),
            ],
            options={
                'verbose_name': 'email change request',
                'verbose_name_plural': 'email change requests',
                'indexes': [models.Index(fields=['account', '-created_at'], name='client_port_account_e57c32_idx'), models.Index(fields=['expires_at'], name='client_port_expires_d97b28_idx')],
            },
        ),
    ]
