# Generated by Django 6.0.4 on 2026-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='avatar_image',
            field=models.TextField(blank=True, default='', help_text='Base64 data URL the customer uploaded as their profile photo. Rendered next to their own messages in the portal chat and on the staff comments side so the team can match a thread to a face. Mirrors ``apps.accounts.User.avatar_image`` so the two surfaces share the same wire shape (opaque string, displayed via ``<img src={value}/>``). When we migrate to blob storage this column becomes a URL — every consumer already treats the value as opaque.', verbose_name='avatar image'),
        ),
    ]
