# Generated by Django 6.0.4 on 2026-05-21 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0003_clientaccount_avatar_image'),
        ('customers', '0002_customer_dynamics_id_customer_dynamics_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortalInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='URL token shared with the customer. The full UUID is the secret — there is no plaintext-hash split here because the customer needs the raw token in the link.', unique=True)),
                ('code_hash', models.CharField(help_text="SHA-256 of the plaintext 6-digit code mailed to the customer's address. Stored hashed so a DB dump can't be turned into a working activation.", max_length=64)),
                ('email_snapshot', models.EmailField(help_text="Customer's email at the moment of invite creation. Pinned here so a later edit to ``Customer.email`` doesn't desync the activate page from the inbox the code was actually sent to.", max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a fresher invite superseded this one. Distinct from ``used_at`` so the audit log can tell a re-issued (abandoned) invite apart from a consumed one.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who issued the invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text="Customer the invite activates. ``on_delete=CASCADE`` so deleting the CRM row sweeps any open invites with it — they'd never be redeemable anyway.", on_delete=django.db.models.deletion.CASCADE, related_name='portal_invites', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer portal invite',
                'verbose_name_plural': 'customer portal invites',
                'indexes': [models.Index(fields=['customer', '-created_at'], name='client_port_custome_262e5c_idx'), models.Index(fields=['expires_at'], name='client_port_expires_dfe507_idx')],
            },
        ),
    ]
