# Generated by Django 6.0.4 on 2026-05-26 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0004_customer_portal_invite'),
        ('organizations', '0014_backfill_proposals_view_all'),
        ('proposals', '0017_proposal_activation_code_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('link_opened', 'Activation link opened'), ('activation_code_requested', 'Verification code requested'), ('activated', 'Account activated'), ('signed_in', 'Signed in'), ('signed_out', 'Signed out'), ('proposal_viewed', 'Proposal opened'), ('proposal_pdf_downloaded', 'Proposal PDF downloaded'), ('proposal_signed', 'Proposal signed'), ('proposal_rejected', 'Proposal rejected'), ('spec_viewed', 'Spec sheet opened'), ('spec_signed', 'Spec sheet signed')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_events', to='client_portal.clientaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_events', to='organizations.organization')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_events', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'portal event',
                'verbose_name_plural': 'portal events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'proposal', '-created_at'], name='client_port_organiz_2141b5_idx'), models.Index(fields=['proposal', 'kind'], name='client_port_proposa_361efa_idx')],
            },
        ),
    ]
