# Generated by Django 6.0.4 on 2026-04-14 18:58

import apps.organizations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('token', models.CharField(default=apps.organizations.models._generate_invitation_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Permissions the invitee will receive on accept.', verbose_name='permissions')),
                ('expires_at', models.DateTimeField(default=apps.organizations.models._default_invitation_expiry, verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['token'], name='organizatio_token_a43b03_idx'), models.Index(fields=['expires_at'], name='organizatio_expires_fb3b75_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('organization', 'email'), name='organizations_invitation_unique_pending_per_org_email')],
            },
        ),
    ]
