# Generated by Django 6.0.4 on 2026-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_permissions_to_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Members can only use the workspace when this is enabled. Superusers always bypass the check.', verbose_name='is active'),
        ),
    ]
