# Generated by Django 6.0.4 on 2026-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_spec_limits',
            field=models.JSONField(blank=True, default=dict, help_text="Organization-level defaults for the spec sheet's ``Microbiological, PAH, Pesticides and Heavy Metal`` block. Keys: ``total_aerobic``, ``total_yeast``, ``e_coli``, ``salmonella``, ``pah``, ``heavy_metal``, ``pesticides``, ``others``. Individual sheets can override via :attr:`SpecificationSheet.limits_override`.", verbose_name='default spec limits'),
        ),
    ]
