# Generated by Django 6.0.4 on 2026-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_membership_orgs_membership_org_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dynamics_config',
            field=models.JSONField(blank=True, default=dict, help_text='Microsoft Dynamics 365 connection settings for this workspace. Empty dict = integration disabled.', verbose_name='dynamics integration config'),
        ),
    ]
