# Generated by Django 6.0.4 on 2026-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_backfill_proposals_manual_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='groups',
            field=models.JSONField(blank=True, default=list, help_text='Role tags for picker scoping (subset of {"scientist", "sales"}).', verbose_name='groups'),
        ),
    ]
