# Generated by Django 6.0.4 on 2026-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_membership_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mrpeasy_config',
            field=models.JSONField(blank=True, default=dict, help_text='MRPEasy connection settings for this workspace. Empty dict = integration disabled.', verbose_name='mrpeasy integration config'),
        ),
    ]
