# Generated by Django 6.0.4 on 2026-05-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_mrpeasy_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wix_cff_config',
            field=models.JSONField(blank=True, default=dict, help_text='Wix Custom Formulation Request form connection settings. Empty dict = integration disabled.', verbose_name='Wix CFF integration config'),
        ),
    ]
