# Generated by Django 6.0.4 on 2026-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_backfill_rtg_catalog_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='psp_config',
            field=models.JSONField(blank=True, default=dict, help_text='PSP (production platform) connection settings. Empty dict = integration disabled. Mutually exclusive with ``mrpeasy_config`` at the settings-page level — enabling one clears the other.', verbose_name='PSP integration config'),
        ),
    ]
