# Generated by Django 6.0.4 on 2026-04-23 11:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organization_default_spec_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text="Primary contact person at the client (e.g. James Brown). Maps to the proposal's ``billto_contactname`` and the ``Dear …`` greeting.", max_length=200, verbose_name='contact name')),
                ('company', models.CharField(blank=True, default='', help_text='Client organization name. Maps to ``customeridname`` in the Dynamics template.', max_length=200, verbose_name='company')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=60, verbose_name='phone')),
                ('invoice_address', models.TextField(blank=True, default='', verbose_name='invoice address')),
                ('delivery_address', models.TextField(blank=True, default='', verbose_name='delivery address')),
                ('notes', models.TextField(blank=True, default='', help_text="Free-text internal notes. Never rendered on the customer-facing proposal — kept for the sales team's context (e.g. 'prefers email, pays late').", verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('company', 'name'),
                'indexes': [models.Index(fields=['organization', 'company'], name='customers_c_organiz_52890e_idx'), models.Index(fields=['organization', 'name'], name='customers_c_organiz_484379_idx'), models.Index(fields=['organization', '-updated_at'], name='customers_c_organiz_5dd497_idx')],
            },
        ),
    ]
