# Generated by Django 6.0.4 on 2026-05-13 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0008_organization_dynamics_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dynamics_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Dataverse contact / account GUID this customer mirrors. Blank for locally-created customers.', null=True, verbose_name='dynamics id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dynamics_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dynamics synced at'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('dynamics_id', None), _negated=True), fields=('organization', 'dynamics_id'), name='customers_unique_dynamics_per_org'),
        ),
    ]
