# Generated by Django 6.0.4 on 2026-05-22 13:38

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_dynamics_id_customer_dynamics_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmailAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="Lower-case-normalised historical address. Always different from the customer's current ``email`` — the writer skips creating an alias for the customer's own canonical address.", max_length=254, verbose_name='email')),
                ('source', models.CharField(choices=[('portal_email_change', 'Portal email change')], default='portal_email_change', max_length=32, verbose_name='source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('customer', models.ForeignKey(help_text='The customer this prior email belonged to. ``CASCADE`` because aliases are intrinsic to their owner; deleting the customer drops them too.', on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer email alias',
                'verbose_name_plural': 'customer email aliases',
                'ordering': ('-created_at',),
                'indexes': [models.Index(django.db.models.functions.text.Lower('email'), name='cust_email_alias_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('customer'), name='customer_email_alias_unique_per_customer')],
            },
        ),
    ]
