# Generated by Django 6.0.4 on 2026-05-22 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customeremailalias'),
        ('organizations', '0014_backfill_proposals_view_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dynamics_account_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Dataverse account GUID — the company this customer represents. New imports key on this so the same business never duplicates into two local rows.', null=True, verbose_name='dynamics account id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dynamics_contact_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="Dataverse contact GUID for the current primary contact. Snapshot of this contact's details lives in name / email / phone / addresses. Swap moves the snapshot to a new contact under the same account.", null=True, verbose_name='dynamics contact id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dynamics_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Legacy Dataverse GUID — populated for customers imported before the account/contact split. New imports populate dynamics_account_id / dynamics_contact_id instead.', null=True, verbose_name='dynamics id'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('dynamics_account_id', None), _negated=True), fields=('organization', 'dynamics_account_id'), name='customers_unique_dynamics_account_per_org'),
        ),
    ]
