export { proposalsEndpoints } from "./endpoints";
export {
  REJECTION_CATEGORIES,
  rejectionCategoryLabel,
  type RejectionCategoryEntry,
  type RejectionCategoryKey,
} from "./rejection-categories";
export {
  addProposalLine,
  cloneRejectedProposal,
  completeProposalRequiredFields,
  extractRetryBlocked,
  type RetryBlockedPayload,
  createProposal,
  createProposalBundle,
  deleteProposal,
  deleteProposalLine,
  fetchCostPreview,
  fetchProposal,
  fetchProposalActivity,
  fetchProposalAttachedSpec,
  fetchProposalAudit,
  fetchProposalLines,
  fetchProposalSavingsAtScale,
  fetchProposalTransitions,
  fetchProposalsPage,
  patchProposalLine,
  sendProposalTestEmail,
  sendProposalToClient,
  transitionProposalStatus,
  updateProposal,
} from "./api";
export type { FetchProposalsPageArgs } from "./api";
export {
  proposalsQueryKeys,
  useAddProposalLine,
  useCloneRejectedProposal,
  useCompleteProposalRequiredFields,
  useCostPreview,
  useCreateProposal,
  useCreateProposalBundle,
  useDeleteProposal,
  useDeleteProposalLine,
  useInfiniteProposals,
  usePatchProposalLine,
  useProposal,
  useProposalActivity,
  useProposalAttachedSpec,
  useProposalAudit,
  useProposalLines,
  useProposalSavingsAtScale,
  useProposalTransitions,
  useProposalsPage,
  useSendProposalTestEmail,
  useSendProposalToClient,
  useSetProposalAdditionalSalesPeople,
  useTransitionProposalStatus,
  useUpdateProposal,
} from "./hooks";
export type { ProposalsListArgs } from "./hooks";
export {
  PROPOSAL_STATUSES,
  PROPOSAL_TEMPLATE_TYPES,
  type CostPreviewDto,
  type CreateProposalBundleRequestDto,
  type CreateProposalLineRequestDto,
  type CreateProposalRequestDto,
  type ProposalBundleEntryDto,
  type PaginatedProposalsDto,
  type ProposalActivityDto,
  type ProposalActivityEventDto,
  type ProposalActivitySummarySlot,
  type ProposalActivityTarget,
  type ProposalAuditDocumentDto,
  type ProposalAuditDto,
  type ProposalAuditSpecDto,
  type ProposalCustomerSignature,
  type ProposalDto,
  type ProposalKioskDto,
  type ProposalKioskSpecDto,
  type ProposalActiveRetryDto,
  type ProposalFollowUpDto,
  type ProposalLineDto,
  type ProposalListItemDto,
  type ProposalPreviousRejectedDto,
  type ProposalSavingsAtScaleDto,
  type ProposalSavingsAtScaleRowDto,
  type ProposalSavingsIngredientRowDto,
  type ProposalSavingsLabourRowDto,
  type ProposalSignatureSlot,
  type ProposalStatus,
  type ProposalStatusRequestDto,
  type ProposalTemplateType,
  type ProposalTransitionDto,
  type UpdateProposalLineRequestDto,
  type UpdateProposalRequestDto,
} from "./types";
export {
  fetchPipelineBoard,
  fetchPipelineColumnPage,
} from "./pipeline";
export type {
  PipelineBoardDto,
  PipelineCardDto,
  PipelineColumnDto,
  PipelineColumnPageDto,
  PipelineScope,
} from "./pipeline";
