"""Models for the label-design workflow.

Shape recap (see plan §Data model):

* :class:`LabelDesign` — one row per project; the workflow root.
* :class:`LabelDesignRevision` — immutable artwork snapshot; every
  rejection produces a new revision.
* :class:`LabelDesignReview` — one row per (revision, reviewer-kind);
  carries the 22-item checklist + mandatory final comments.
* :class:`LabelDesignPreferences` — MA-ST-B-009 form, populated on
  the DESIGN_BY_US path.
* :class:`LabelDesignPreferenceFile` — inspiration attachments
  uploaded with the preferences form.
* :class:`LabelDesignTransition` — append-only audit row written
  inside the same transaction as the status change.

The state machine + transition validator live in
:mod:`apps.label_design.services`; the constants (status enums,
allowed transitions, checklist tuple) live in
:mod:`apps.label_design.constants` so they can be imported without
touching the model layer.
"""

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.label_design.constants import (
    DesignStyle,
    LabelDesignPath,
    LabelDesignStatus,
    MaterialType,
    ReviewKind,
    ReviewOutcome,
    RevisionSource,
)


_ALLOWED_ARTWORK_EXTS = {".pdf", ".png", ".jpg", ".jpeg"}


def _safe_extension(filename: str, fallback: str = ".bin") -> str:
    """Return a lowercase, safe file extension from ``filename``.

    Defends the Azure / local storage layer from customer-supplied
    filenames with weird casing, double extensions, or non-ASCII
    characters that would otherwise leak straight into the blob
    name and fight every downstream tool. Falls back to
    ``fallback`` when nothing recognisable is present.
    """

    from pathlib import Path

    suffix = Path(filename or "").suffix.lower()
    if not suffix or any(c for c in suffix if c not in "abcdefghijklmnopqrstuvwxyz0123456789."):
        return fallback
    return suffix


def _revision_artwork_upload_to(instance: "LabelDesignRevision", filename: str) -> str:
    """Storage path for revision artwork PDFs / images.

    Always renames the uploaded file to ``artwork.<ext>`` under
    a UUID-keyed folder per revision so:

    * The full blob name is deterministic and short (well under
      the 255-char DB column AND the 1024-char Azure blob name
      cap) — no risk of ``SuspiciousFileOperation`` on collision.
    * The customer-supplied filename (which may contain spaces,
      Unicode, parentheses, etc.) never lands on the wire as part
      of the blob path; Azure / S3 / on-disk all see the same
      sanitised name.
    * The revision UUID guarantees uniqueness, so Django's
      collision-suffix routine never fires.
    """

    ext = _safe_extension(filename, fallback=".pdf")
    return (
        f"label_design/{instance.label_design_id}/revisions/"
        f"{instance.id}/artwork{ext}"
    )


def _revision_preview_upload_to(instance: "LabelDesignRevision", filename: str) -> str:
    """Storage path for the auto-generated preview PNG.

    Mirrors :func:`_revision_artwork_upload_to`: fixed
    ``preview.png`` name under the revision's UUID folder. The
    preview is always a PNG (generated by the artwork renderer),
    so the extension is hard-coded rather than sniffed.
    """

    return (
        f"label_design/{instance.label_design_id}/revisions/"
        f"{instance.id}/preview.png"
    )


def _preference_file_upload_to(instance: "LabelDesignPreferenceFile", filename: str) -> str:
    """Storage path for customer-uploaded inspiration files.

    One row per file, so ``instance.id`` (UUID) is the natural
    uniqueness anchor — we use it as the file's base name so the
    customer's original filename never touches the blob path.
    Preserves the file extension because the renderer / preview
    layer keys content type off it.
    """

    ext = _safe_extension(filename)
    return (
        f"label_design/{instance.preferences.label_design_id}/"
        f"inspiration/{instance.id}{ext}"
    )


class LabelDesign(models.Model):
    """The workflow root: one row per project that has reached the
    label-design phase.

    Created by signal when :class:`apps.formulations.models.Formulation`
    hits ``APPROVED`` AND a customer-signed spec sheet exists. The
    starting status is ``PAYMENT_PENDING`` because the finance team
    still needs to record a payment before the customer can pick a
    design path.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="label_designs",
    )
    formulation = models.ForeignKey(
        "formulations.Formulation",
        on_delete=models.CASCADE,
        related_name="label_designs",
        help_text=_(
            "The formulation (product) this label workflow covers. "
            "One LabelDesign per (formulation, proposal) pair — "
            "Custom projects have one proposal today so this stays "
            "1:1 per formulation; RTG catalog products get ordered "
            "N times and each order's proposal spawns its own label "
            "workflow so revisions + approvals stay scoped to the "
            "order the customer is looking at."
        ),
    )
    proposal = models.ForeignKey(
        "proposals.Proposal",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="label_designs",
        help_text=_(
            "The proposal / customer order this label belongs to. "
            "Nullable for legacy rows created before the per-proposal "
            "split; new rows always populate. Combined with "
            "``formulation`` as the uniqueness key so a customer "
            "placing a second RTG order on the same catalog product "
            "gets a fresh label workflow instead of reusing the "
            "first order's."
        ),
    )
    specification_sheet = models.ForeignKey(
        "specifications.SpecificationSheet",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="label_designs",
        help_text=_(
            "The customer-signed final spec sheet whose acceptance "
            "gated entry to this workflow. Kept for audit — points "
            "at the spec whose signature originally triggered the "
            "bootstrap. SET_NULL on delete because losing the spec "
            "row shouldn't cascade into losing the label workflow "
            "that followed from it."
        ),
    )

    status = models.CharField(
        _("status"),
        max_length=32,
        choices=LabelDesignStatus.choices,
        default=LabelDesignStatus.PAYMENT_PENDING,
        db_index=True,
    )
    design_path = models.CharField(
        _("design path"),
        max_length=24,
        choices=LabelDesignPath.choices,
        blank=True,
        default="",
        help_text=_(
            "Which side does the artistic work. Blank until the customer "
            "picks on the portal."
        ),
    )

    current_revision = models.ForeignKey(
        "LabelDesignRevision",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        help_text=_(
            "Denormalised pointer to the revision currently in review "
            "or approved. Avoids a subquery on the hot path."
        ),
    )
    preferences = models.OneToOneField(
        "LabelDesignPreferences",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="label_design_link",
        help_text=_(
            "MA-ST-B-009 form payload. Only populated on the "
            "DESIGN_BY_US path."
        ),
    )

    assigned_designer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_label_designs",
    )

    rejection_count = models.PositiveSmallIntegerField(
        _("consecutive customer rejections"),
        default=0,
        help_text=_(
            "Bumped each time the customer rejects on the "
            "CUSTOMER_APPROVAL step; reset when the next customer "
            "approval lands. The transition service auto-routes to "
            "``ON_HOLD`` once this exceeds "
            "``MAX_CUSTOMER_REJECTIONS_BEFORE_HOLD``."
        ),
    )

    # Customer approval — mirrors the SpecificationSheet ESIGN columns
    # at apps/specifications/models.py:196-239. Lets the same legal
    # defence apply to a label sign-off as to the underlying spec.
    customer_approved_at = models.DateTimeField(
        _("customer approved at"), null=True, blank=True
    )
    customer_approved_by = models.ForeignKey(
        "client_portal.ClientAccount",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_label_designs",
    )
    customer_approval_signature_image = models.TextField(
        _("customer approval signature image"),
        blank=True,
        default="",
        help_text=_(
            "Base64-encoded PNG data URL captured on the portal "
            "signature pad."
        ),
    )
    customer_sign_ip = models.CharField(
        _("customer sign ip"), max_length=45, blank=True, default=""
    )
    customer_sign_user_agent = models.TextField(
        _("customer sign user agent"), blank=True, default=""
    )
    customer_sign_document_hash = models.CharField(
        _("customer sign document hash"),
        max_length=64,
        blank=True,
        default="",
        help_text=_(
            "SHA-256 hex digest of the rendered approval HTML the "
            "customer saw at sign time. ESIGN drift detector."
        ),
    )

    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("label design")
        verbose_name_plural = _("label designs")
        ordering = ("-updated_at",)
        indexes = [
            models.Index(fields=("organization", "status")),
            models.Index(fields=("organization", "-updated_at")),
            # Per-formulation lookups are hot: the dashboard, the
            # staff queue, and the payment-approval fan-out walk
            # every label-design row for a project. Per-proposal
            # lookups back the RTG multi-order portal disambiguation.
            models.Index(fields=("formulation",)),
            models.Index(fields=("proposal",)),
        ]
        constraints = [
            # One label workflow per (formulation, proposal). Custom
            # projects have a single proposal today so this behaves
            # exactly like the old ``formulation``-only constraint;
            # RTG catalog orders each get their own proposal and
            # therefore their own label workflow (each customer order
            # is an independent business object — the same product
            # ordered twice does NOT share a label queue).
            #
            # Postgres treats NULL != NULL in unique constraints, so
            # legacy rows with ``proposal IS NULL`` (pre-migration
            # data before the split) can co-exist with new
            # per-proposal rows without a UNIQUE violation on
            # re-bootstrap.
            models.UniqueConstraint(
                fields=("formulation", "proposal"),
                name="label_design_unique_per_formulation_proposal",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover - admin display
        return f"LabelDesign({self.formulation_id}, {self.status})"


class LabelDesignRevision(models.Model):
    """One artwork submission. Immutable — every rejection writes a
    new row rather than overwriting the previous one, so the audit
    trail survives and reviewers can diff iterations.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    label_design = models.ForeignKey(
        LabelDesign,
        on_delete=models.CASCADE,
        related_name="revisions",
    )
    revision_number = models.PositiveIntegerField(
        _("revision number"),
        help_text=_(
            "Monotonic per label_design; assigned by the service layer "
            "at submit time. Numbering starts at 1."
        ),
    )

    submitted_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="submitted_label_revisions",
        help_text=_(
            "Staff designer who submitted this revision. Null when "
            "the customer self-designed."
        ),
    )
    submitted_by_client = models.ForeignKey(
        "client_portal.ClientAccount",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="submitted_label_revisions",
        help_text=_(
            "Portal customer who submitted this revision. Null when "
            "a staff designer submitted."
        ),
    )
    submitted_at = models.DateTimeField(default=timezone.now, editable=False)
    source = models.CharField(
        _("source"),
        max_length=24,
        choices=RevisionSource.choices,
    )

    # ``max_length=255`` because the default 100 isn't enough for
    # the ``label_design/<ld_id>/revisions/<revision_id>/<file>``
    # path scheme — the two UUID segments alone consume ~85 chars,
    # leaving Django's collision-suffix routine no room to add a
    # ``_XxXxXxX`` discriminator without raising
    # ``SuspiciousFileOperation``.
    artwork_pdf = models.FileField(
        _("artwork PDF"),
        upload_to=_revision_artwork_upload_to,
        max_length=255,
        blank=True,
        null=True,
        help_text=_(
            "Canonical archived artwork file. Stored on the Azure "
            "container in production, on the local filesystem in dev."
        ),
    )
    artwork_preview_png = models.FileField(
        _("preview PNG"),
        upload_to=_revision_preview_upload_to,
        max_length=255,
        blank=True,
        null=True,
        help_text=_(
            "Auto-generated thumbnail rendered from the artwork PDF "
            "for the list / workspace surfaces."
        ),
    )

    compliance_block_snapshot = models.JSONField(
        _("compliance block snapshot"),
        default=dict,
        blank=True,
        help_text=_(
            "Frozen content-block dict at submit time. Lets reviewers "
            "compare what was required vs what was delivered, and "
            "survives later spec edits — see plan §Spec drift risk."
        ),
    )

    customer_approved_own_design = models.BooleanField(
        _("customer approved own design"),
        default=False,
        help_text=_(
            "True when the customer self-designed and uploaded the "
            "artwork; the explicit CUSTOMER_APPROVAL step is skipped "
            "because this acts as their approval."
        ),
    )
    notes = models.TextField(_("notes"), blank=True, default="")

    class Meta:
        verbose_name = _("label design revision")
        verbose_name_plural = _("label design revisions")
        ordering = ("-submitted_at",)
        constraints = [
            models.UniqueConstraint(
                fields=("label_design", "revision_number"),
                name="label_design_revision_unique_number",
            ),
        ]
        indexes = [
            models.Index(fields=("label_design", "-revision_number")),
        ]

    def __str__(self) -> str:  # pragma: no cover - admin display
        return f"Revision {self.revision_number} of {self.label_design_id}"


def _revision_asset_upload_to(
    instance: "LabelDesignRevisionAsset", filename: str
) -> str:
    """Storage path for supplementary revision assets.

    One folder per revision (mirrors ``_revision_artwork_upload_to``)
    with a UUID-keyed asset filename inside so a customer uploading
    two files both called ``front.pdf`` doesn't collide on save.
    Extension preserved so browsers pick the right renderer when
    the URL is opened directly.
    """

    ext = _safe_extension(filename, fallback="")
    return (
        f"label_design/{instance.revision.label_design_id}/revisions/"
        f"{instance.revision_id}/assets/{instance.id}{ext}"
    )


class LabelDesignRevisionAsset(models.Model):
    """One supplementary artwork file attached to a revision — the
    "back view", "side view", "mockup on shelf" companions to the
    canonical ``LabelDesignRevision.artwork_pdf``.

    Kept as a related model (not a JSONB column on the parent) so:

    * Each file has its own storage path + audit history — the
      immutable revision-per-submission audit contract still holds.
    * File-count limits and per-file validation apply per row via
      the standard :func:`_validate_artwork_file` helper.
    * Deletion / reorder edits don't rewrite the parent revision.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    revision = models.ForeignKey(
        LabelDesignRevision,
        on_delete=models.CASCADE,
        related_name="additional_assets",
    )
    file = models.FileField(
        _("file"),
        upload_to=_revision_asset_upload_to,
        max_length=255,
    )
    #: Optional label the uploader gave the view — "Back", "Left side",
    #: "Mockup on 500ml bottle". Empty string when the uploader didn't
    #: bother — the FE falls back to "View {N}" in that case.
    label = models.CharField(
        _("view label"), max_length=80, blank=True, default=""
    )
    #: Preserves the browser-side ordering so a customer who dragged
    #: "Front" above "Back" sees the same order on both sides.
    sort_order = models.PositiveIntegerField(
        _("sort order"), default=0, db_index=True
    )
    original_filename = models.CharField(
        _("original filename"), max_length=255, blank=True, default=""
    )
    content_type = models.CharField(
        _("content type"), max_length=120, blank=True, default=""
    )
    size_bytes = models.PositiveIntegerField(_("size in bytes"), default=0)

    created_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = _("label design revision asset")
        verbose_name_plural = _("label design revision assets")
        ordering = ("sort_order", "created_at")
        indexes = [
            models.Index(fields=("revision", "sort_order")),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"Asset {self.id} of revision {self.revision_id}"


class LabelDesignReview(models.Model):
    """A scientist's or director's verdict on a single revision.

    Unique on ``(revision, kind)`` so the same role cannot review
    the same revision twice — a rejection produces a new revision,
    which gets its own review row.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    revision = models.ForeignKey(
        LabelDesignRevision,
        on_delete=models.CASCADE,
        related_name="reviews",
    )
    kind = models.CharField(
        _("kind"),
        max_length=16,
        choices=ReviewKind.choices,
    )
    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="label_reviews",
    )
    outcome = models.CharField(
        _("outcome"),
        max_length=24,
        choices=ReviewOutcome.choices,
    )
    checklist_responses = models.JSONField(
        _("checklist responses"),
        default=list,
        help_text=_(
            "List of ``{item_key, pass, comment}``. Validated by the "
            "review serializer against "
            "``constants.COMPLIANCE_CHECKLIST_KEYS`` — every checklist "
            "item must be present, no extras allowed."
        ),
    )
    final_comments = models.TextField(
        _("final comments"),
        help_text=_(
            "Mandatory — the regulatory team requires reviewers to "
            "describe exactly what they reviewed. Enforced at the "
            "serializer + service layer."
        ),
    )
    signature_image = models.TextField(
        _("signature image"),
        blank=True,
        default="",
        help_text=_(
            "Base64-encoded signature pad capture. Same shape as the "
            "prepared-by / director signatures on SpecificationSheet."
        ),
    )
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = _("label design review")
        verbose_name_plural = _("label design reviews")
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(
                fields=("revision", "kind"),
                name="label_design_review_unique_per_revision_kind",
            ),
        ]
        indexes = [
            models.Index(fields=("revision", "kind")),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.kind} review of {self.revision_id}: {self.outcome}"


class LabelDesignPreferences(models.Model):
    """MA-ST-B-009 Design Preferences Form payload.

    Populated only on the DESIGN_BY_US path. The OneToOne back to
    :class:`LabelDesign` is on ``LabelDesign.preferences`` — kept on
    the parent so the workflow row can be queried without joining
    against a sibling that may or may not exist.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    submitted_by_client = models.ForeignKey(
        "client_portal.ClientAccount",
        on_delete=models.PROTECT,
        related_name="submitted_label_preferences",
    )
    submitted_at = models.DateTimeField(default=timezone.now, editable=False)

    # Section: Company Information
    # Auto-populated from the Customer record on submit but persisted
    # here too because the customer can override (e.g. "we go by 'Acme
    # Skin Co' on the label even though the contract is 'Acme Limited'").
    company_name = models.CharField(max_length=200, blank=True, default="")
    brand_name = models.CharField(max_length=200, blank=True, default="")
    product_names = models.TextField(blank=True, default="")
    product_codes = models.TextField(blank=True, default="")

    # Section: Design
    brand_colours = models.JSONField(
        _("brand colours"),
        default=list,
        blank=True,
        help_text=_(
            'List of ``{ "name": "...", "hex": "#..." }`` entries.'
        ),
    )
    inspiration_urls = models.JSONField(
        _("inspiration URLs"),
        default=list,
        blank=True,
        help_text=_(
            "List of URL strings the customer referenced as visual "
            "inspiration."
        ),
    )
    elements_to_include = models.TextField(
        _("specific elements to include"), blank=True, default=""
    )
    design_style = models.CharField(
        _("design style"),
        max_length=16,
        choices=DesignStyle.choices,
        blank=True,
        default="",
    )
    material_type = models.CharField(
        _("material type"),
        max_length=16,
        choices=MaterialType.choices,
        blank=True,
        default="",
    )

    # Section: Others
    additional_comments = models.TextField(
        _("additional comments"), blank=True, default=""
    )

    # Declaration + signature
    declaration_signed_at = models.DateTimeField(
        _("declaration signed at"), null=True, blank=True
    )
    declaration_signature_image = models.TextField(
        _("declaration signature image"), blank=True, default=""
    )
    declaration_name = models.CharField(max_length=200, blank=True, default="")
    declaration_position = models.CharField(max_length=120, blank=True, default="")

    # Forward-compatible raw payload — mirrors CFFSubmission.raw_payload
    # so a future revision of the form can keep landing without a model
    # migration on day one.
    raw_payload = models.JSONField(
        _("raw payload"),
        default=dict,
        blank=True,
    )

    class Meta:
        verbose_name = _("label design preferences")
        verbose_name_plural = _("label design preferences")
        ordering = ("-submitted_at",)

    def __str__(self) -> str:  # pragma: no cover
        return f"Preferences {self.id}"


class LabelDesignPreferenceFile(models.Model):
    """One inspiration file uploaded with the design preferences form."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    preferences = models.ForeignKey(
        LabelDesignPreferences,
        on_delete=models.CASCADE,
        related_name="inspiration_files",
    )
    # ``max_length=255`` for the same reason the artwork FileFields
    # carry it — the long UUID-laden ``upload_to`` path leaves no
    # room under Django's default 100-char cap.
    file = models.FileField(
        upload_to=_preference_file_upload_to, max_length=255
    )
    original_name = models.CharField(max_length=255, blank=True, default="")
    content_type = models.CharField(max_length=120, blank=True, default="")
    size_bytes = models.PositiveBigIntegerField(default=0)
    uploaded_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = _("label design inspiration file")
        verbose_name_plural = _("label design inspiration files")
        ordering = ("uploaded_at",)


class LabelDesignTransition(models.Model):
    """Append-only audit row written inside the same transaction as
    a status flip on :class:`LabelDesign`.

    Either ``actor`` (staff User) or ``actor_client_account`` is set
    — never both. The system signal that bootstraps the row on spec
    customer-sign records ``actor=NULL`` + ``actor_client_account=
    NULL`` + ``notes='system'`` so the timeline reads cleanly.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    label_design = models.ForeignKey(
        LabelDesign,
        on_delete=models.CASCADE,
        related_name="transitions",
    )
    from_status = models.CharField(
        _("from status"),
        max_length=32,
        choices=LabelDesignStatus.choices,
        blank=True,
        default="",
        help_text=_(
            "Status the workflow left. Blank when the row is created "
            "by the bootstrap signal (no prior status)."
        ),
    )
    to_status = models.CharField(
        _("to status"),
        max_length=32,
        choices=LabelDesignStatus.choices,
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="label_design_transitions",
    )
    actor_client_account = models.ForeignKey(
        "client_portal.ClientAccount",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="label_design_transitions",
    )
    notes = models.TextField(
        _("notes"),
        blank=True,
        default="",
    )
    metadata = models.JSONField(
        _("metadata"),
        default=dict,
        blank=True,
        help_text=_(
            "Free-form keys: revision_id / review_id / payment_id "
            "depending on which trigger fired the transition."
        ),
    )
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = _("label design transition")
        verbose_name_plural = _("label design transitions")
        ordering = ("-created_at",)
        indexes = [
            models.Index(fields=("label_design", "-created_at")),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.label_design_id}: {self.from_status} → {self.to_status}"


# ---------------------------------------------------------------------------
# Template library — staff-curated design resources the customer can
# download to use when they're on the DESIGN_BY_CUSTOMER path.
# ---------------------------------------------------------------------------


def _template_upload_to(instance: "LabelDesignTemplate", filename: str) -> str:
    """Storage path for a customer-downloadable template.

    Uploaded files keep their ORIGINAL filename (the customer
    downloads ``Capsule-Label-A4.psd`` not
    ``template.bin``) but the on-disk path is namespaced by org +
    template id so two templates with the same name across two
    organisations can't collide.
    """

    from pathlib import Path

    safe_name = Path(filename or "template").name.replace("/", "_") or "template"
    return f"label_design_templates/{instance.organization_id}/{instance.id}/{safe_name}"


class LabelDesignTemplateCategory(models.Model):
    """Top-level grouping for downloadable label-design templates.

    Org-scoped because each Vita organisation curates its own
    template library (e.g. one org sells supplements in capsule
    form, another sells liquids — the relevant template surfaces
    differ). Categories are presentation-only: customers see the
    name + ordering, no permission gates per category.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="label_design_template_categories",
    )
    name = models.CharField(_("name"), max_length=120)
    description = models.TextField(_("description"), blank=True, default="")
    sort_order = models.PositiveIntegerField(
        _("sort order"),
        default=0,
        help_text=_(
            "Lower numbers render first. Lets staff curate the order "
            "without renaming categories."
        ),
    )

    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("label design template category")
        verbose_name_plural = _("label design template categories")
        ordering = ("sort_order", "name")
        constraints = [
            # Names are unique per org so the customer doesn't see
            # two "Capsule labels" cards.
            models.UniqueConstraint(
                fields=("organization", "name"),
                name="label_design_template_category_unique_name",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover - admin display
        return self.name


class LabelDesignTemplate(models.Model):
    """A single downloadable file in the template library.

    Org-scoped: customers see templates from the org that owns
    their projects. The actual file lives on the same storage
    backend the artwork uses (Azure Blob in prod, local FS in
    dev) so the existing CDN / lifecycle policies apply.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="label_design_templates",
    )
    category = models.ForeignKey(
        LabelDesignTemplateCategory,
        on_delete=models.PROTECT,
        related_name="templates",
        help_text=_(
            "PROTECT because deleting a category that still has "
            "templates attached would silently break customer "
            "downloads — staff has to clear the category first."
        ),
    )
    name = models.CharField(_("name"), max_length=180)
    description = models.TextField(_("description"), blank=True, default="")
    file = models.FileField(
        _("file"),
        upload_to=_template_upload_to,
        max_length=255,
        help_text=_(
            "Any file type accepted (PDF, PNG, JPG, AI, PSD, ZIP, …). "
            "The Azure container the file lands in inherits the "
            "media-container ACL — public read; staff-managed write."
        ),
    )
    file_original_name = models.CharField(
        _("original filename"),
        max_length=255,
        blank=True,
        default="",
        help_text=_(
            "Customer-visible filename at upload time. Used to seed "
            "the Content-Disposition header on download so the file "
            "lands with a sensible name on the customer's disk."
        ),
    )
    file_size_bytes = models.PositiveBigIntegerField(
        _("file size (bytes)"),
        default=0,
        help_text=_(
            "Captured at upload time; the FE renders it as KB / MB "
            "next to the download button so customers know what "
            "they're about to fetch."
        ),
    )
    content_type = models.CharField(
        _("content type"),
        max_length=120,
        blank=True,
        default="",
        help_text=_(
            "MIME type sniffed at upload time. Used to render an "
            "appropriate icon + as a hint for the download header."
        ),
    )
    sort_order = models.PositiveIntegerField(_("sort order"), default=0)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="uploaded_label_design_templates",
    )
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("label design template")
        verbose_name_plural = _("label design templates")
        ordering = ("sort_order", "name")
        indexes = [
            models.Index(fields=("organization", "category", "sort_order")),
        ]

    def __str__(self) -> str:  # pragma: no cover - admin display
        return self.name
