# Generated by Django 6.0.4 on 2026-04-15 18:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Internal product code. Optional, unique per org when set.', max_length=64, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('dosage_form', models.CharField(choices=[('powder', 'Powder'), ('capsule', 'Capsule'), ('tablet', 'Tablet'), ('gummy', 'Gummy'), ('liquid', 'Liquid'), ('other_solid', 'Other solid')], default='capsule', max_length=32, verbose_name='dosage form')),
                ('capsule_size', models.CharField(blank=True, default='', max_length=32, verbose_name='capsule size')),
                ('tablet_size', models.CharField(blank=True, default='', max_length=32, verbose_name='tablet size')),
                ('serving_size', models.PositiveIntegerField(default=1, help_text='Units (capsules/tablets/scoops) the customer consumes per serving.', verbose_name='serving size')),
                ('servings_per_pack', models.PositiveIntegerField(default=60, verbose_name='servings per pack')),
                ('directions_of_use', models.TextField(blank=True, default='', verbose_name='directions of use')),
                ('suggested_dosage', models.TextField(blank=True, default='', verbose_name='suggested dosage')),
                ('appearance', models.CharField(blank=True, default='', max_length=200, verbose_name='appearance')),
                ('disintegration_spec', models.CharField(blank=True, default='', help_text="Target disintegration time (e.g. 'within 60 minutes').", max_length=200, verbose_name='disintegration spec')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_formulations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_formulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulation',
                'verbose_name_plural': 'formulations',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='FormulationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('label_claim_mg', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='label claim (mg)')),
                ('serving_size_override', models.PositiveIntegerField(blank=True, help_text="Per-line override; falls back to the formulation's serving size.", null=True, verbose_name='serving size override')),
                ('mg_per_serving_cached', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='mg per serving (cached)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='formulations.formulation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulation_lines', to='catalogues.item')),
            ],
            options={
                'verbose_name': 'formulation line',
                'verbose_name_plural': 'formulation lines',
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='FormulationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('label', models.CharField(blank=True, default='', help_text="Short scientist-written note (e.g. 'caffeine bumped to 200mg').", max_length=150, verbose_name='label')),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict, verbose_name='snapshot metadata')),
                ('snapshot_lines', models.JSONField(blank=True, default=list, verbose_name='snapshot lines')),
                ('snapshot_totals', models.JSONField(blank=True, default=dict, verbose_name='snapshot totals')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_formulation_versions', to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'formulation version',
                'verbose_name_plural': 'formulation versions',
                'ordering': ('-version_number',),
            },
        ),
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['organization', 'status'], name='formulation_organiz_fbdca7_idx'),
        ),
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['organization', '-updated_at'], name='formulation_organiz_e2f3fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='formulation',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='formulations_unique_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='formulationline',
            index=models.Index(fields=['formulation', 'display_order'], name='formulation_formula_db69d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='formulationversion',
            constraint=models.UniqueConstraint(fields=('formulation', 'version_number'), name='formulations_version_unique_number_per_formulation'),
        ),
    ]
