# Generated by Django 6.0.4 on 2026-04-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0005_backfill_snapshot_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='project_status',
            field=models.CharField(choices=[('concept', 'Concept'), ('in_development', 'In development'), ('pilot', 'Pilot'), ('approved', 'Approved'), ('discontinued', 'Discontinued')], db_index=True, default='concept', help_text='Product-roadmap position. Drives the chip shown at the top of the project workspace and the project list filter.', max_length=16, verbose_name='project status'),
        ),
    ]
