# Generated by Django 6.0.4 on 2026-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0006_formulation_project_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formulation',
            name='formulation_organiz_fbdca7_idx',
        ),
        migrations.RemoveField(
            model_name='formulation',
            name='status',
        ),
    ]
