# Generated by Django 6.0.4 on 2026-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0013_formulation_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='approved_version_number',
            field=models.PositiveIntegerField(blank=True, help_text='Points at the :class:`FormulationVersion` snapshot the scientist marked as the current approved recipe. Every version picker in the app (trial batch, spec sheet, QC) badges this number so a teammate never plans a procurement run off a stale draft.', null=True, verbose_name='approved version number'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='target_fill_weight_mg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target fill weight per serving unit — sachet mass for powders, single-gummy weight for gummies. Drives the fill-weight check (total ingredients should equal this target). Leave blank for capsule/tablet where the math uses the selected size instead.', max_digits=12, null=True, verbose_name='target fill weight (mg)'),
        ),
    ]
