# Generated by Django 6.0.4 on 2026-04-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0014_alter_formulation_approved_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='gummy_base_item',
            field=models.ForeignKey(blank=True, help_text="Raw-material item used as the 65% gummy base — Xylitol, Maltitol, Pectin, Gelatin, etc. Picked from the raw_materials catalogue filtered to use_as ∈ (Sweeteners, Bulking Agent). When set, the auto-fill pulls the item's real ingredient_list_name + nutrition + compliance flags so the spec sheet reads accurately; when blank the auto-fill emits a generic 'Gummy Base' row with no nutrition contribution. Ignored for non-gummy forms.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gummy_base_formulations', to='catalogues.item', verbose_name='gummy base item'),
        ),
    ]
