# Generated by Django 6.0.4 on 2026-04-24 14:35 — hand-edited to add
# a data-copy pass so existing single-pick gummy bases carry into the
# new M2M relation before the FK column is dropped.

from django.db import migrations, models


def _copy_fk_to_m2m(apps, schema_editor):
    """Promote the legacy single FK pick onto the new M2M.

    Runs while the ``gummy_base_item`` FK still exists on the model
    (we do this step before ``RemoveField``), so every Formulation
    with a single-pick value enters the new world with that item
    already present in the ``gummy_base_items`` relation. No-op for
    rows where the FK was null or for orgs that never used the field.
    """

    Formulation = apps.get_model("formulations", "Formulation")
    for formulation in Formulation.objects.exclude(
        gummy_base_item__isnull=True
    ).only("id", "gummy_base_item_id"):
        formulation.gummy_base_items.add(formulation.gummy_base_item_id)


def _revert_noop(apps, schema_editor):
    """Reverse direction is destructive (we'd have to pick one item
    from the M2M to write back into a nullable FK). The operation is
    a no-op on downgrade; callers who need to reverse must handle the
    data restore themselves."""

    return


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0015_formulation_gummy_base_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='gummy_base_items',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Raw-material items that make up the gummy base — "
                    "e.g. a Xylitol + Maltitol blend. Each pick must "
                    "have use_as ∈ (Sweeteners, Bulking Agent). The "
                    "base total (target − water − actives − flavour, "
                    "min 65% of target) is split **equally** across "
                    "picked items. Nutrition + compliance + label copy "
                    "flow from every picked item into the spec sheet "
                    "under the EU category label (e.g. 'Sweeteners "
                    "(Xylitol, Maltitol)'). Ignored for non-gummy "
                    "forms."
                ),
                related_name='gummy_base_formulations',
                to='catalogues.item',
                verbose_name='gummy base items',
            ),
        ),
        migrations.RunPython(_copy_fk_to_m2m, _revert_noop),
        migrations.RemoveField(
            model_name='formulation',
            name='gummy_base_item',
        ),
    ]
