# Generated by Django 6.0.4 on 2026-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0016_gummy_base_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='flavour_colour_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items that make up the Flavouring and Colour block — e.g. Natural Strawberry Flavour + Beetroot Extract. Each pick must have use_as = 'Flavouring and Colour'. The total flavour mass (100 mg reference on a gummy) is split **equally** across picks so the spec sheet declaration reads 'Flavouring and Colour (Natural Strawberry Flavour, Beetroot Extract)' with real procurement codes behind each name. Ignored for non-gummy forms.", related_name='flavour_colour_formulations', to='catalogues.item', verbose_name='flavour & colour items'),
        ),
    ]
