# Generated by Django 6.0.4 on 2026-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0017_flavour_colour_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='glazing_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items applied as the surface glaze on a finished gummy — carnauba wax, coconut oil, beeswax, shellac, etc. Each pick must have use_as = 'Glazing Agent'. The glaze total (1% of target gummy weight) is split **equally** across picks; the declaration groups them as 'Glazing Agent (Carnauba Wax, Coconut Oil)'. Ignored for non-gummy forms.", related_name='glazing_formulations', to='catalogues.item', verbose_name='glazing agent items'),
        ),
    ]
