# Generated by Django 6.0.4 on 2026-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0020_gelling_premix_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='gelling_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the gel matrix on a gummy — pectin, gelatin, agar, carrageenan, etc. Each pick must carry use_as = 'Gelling Agent'. The gelling total (3% of target gummy weight, default) splits **equally** across picks; the declaration groups them as 'Gelling Agent (Pectin)'. An empty pick list means a non-gelling gummy and skips the gelling + premix-sweetener bands entirely. Ignored for non-gummy forms.", related_name='gelling_formulations', to='catalogues.item', verbose_name='gelling agent items'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='glazing_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items applied as the surface glaze on a finished gummy — carnauba wax, coconut oil, beeswax, shellac, etc. Each pick must have use_as = 'Glazing Agent'. The glaze total (0.1% of target gummy weight) is split **equally** across picks; the declaration groups them as 'Glazing Agent (Carnauba Wax, Coconut Oil)'. Ignored for non-gummy forms.", related_name='glazing_formulations', to='catalogues.item', verbose_name='glazing agent items'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='premix_sweetener_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items combined with the gelling agent to form the in-house 'Pectin Premix' line on the MRPeasy BOM — typically maltitol, xylitol, sucrose. Picks pull from the same catalogue pool as the gummy base (use_as ∈ Sweeteners, Bulking Agent). The premix-sweetener total (6% of target, default) is **carved out** of the gummy base remainder so the visible base shrinks accordingly. Only emitted when gelling items are also picked.", related_name='premix_sweetener_formulations', to='catalogues.item', verbose_name='premix sweetener items'),
        ),
    ]
