# Generated by Django 6.0.4 on 2026-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0025_formulationline_purity_overage_extract_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='dcp_carrier_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the DCP (dicalcium phosphate) carrier on a tablet. Each pick must carry use_as = 'Bulking Agent'. The DCP total (10% of total active) splits **equally** across picks; same per-pick row + label + nutrition flow as the MCC carrier picker. Empty list falls back to the generic 'Dicalcium Phosphate' placeholder. Ignored for non-tablet forms.", related_name='dcp_carrier_formulations', to='catalogues.item', verbose_name='DCP carrier items'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='mcc_carrier_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the MCC (microcrystalline cellulose) carrier on a capsule or tablet. Each pick must carry use_as = 'Bulking Agent'. The MCC total (remainder for capsules, fixed ratio for tablets) splits **equally** across picks; the declaration emits one row per pick with the picked item's ingredient_list_name + nutrition + compliance flags flowing through. Empty list falls back to the generic 'Microcrystalline Cellulose (Carrier)' placeholder so legacy formulations keep rendering — the spec sheet surfaces a soft warning so the scientist knows to tighten it up. Ignored for powders / gummies.", related_name='mcc_carrier_formulations', to='catalogues.item', verbose_name='MCC carrier items'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='colour_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as colours — e.g. Beetroot Extract, Turmeric Oleoresin, Spirulina Powder. Each pick must carry use_as = 'Colour'. The colour total splits equally across picks and groups as 'Colour (Beetroot Extract, Turmeric)' on the spec sheet. Used by both gummies (2% of target weight) and powders (0.04 mg/ml × water volume).", related_name='colour_formulations', to='catalogues.item', verbose_name='colour items'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='sweetener_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the sweetener on a powder — Sucralose, Stevia, Steviol, etc. Each pick must carry use_as = 'Sweeteners'. The sweetener total (0.06 mg/ml × water volume) splits equally across picks and groups as 'Sweetener (Sucralose, Stevia)' on the spec sheet. Empty list keeps the generic placeholder. Ignored for non-powder forms — gummies use ``gummy_base_items`` and ``premix_sweetener_items`` instead.", related_name='sweetener_formulations', to='catalogues.item', verbose_name='sweetener items'),
        ),
    ]
