# Generated by Django 6.0.4 on 2026-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0026_formulation_dcp_carrier_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='anti_caking_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the combined anti-caking agent on a capsule or tablet (typically Magnesium Stearate + Silicon Dioxide, but any item tagged use_as = 'Anti-caking Agent' is admissible). The combined anti-caking total (1.4% of total active, preserving the historical 1% stearate + 0.4% silica split as one combined band) is split equally across picks; the declaration emits one 'Anti-caking Agents (picked names)' row. **Empty list = no anti-caking on the formulation at all** -- the spec sheet drops the row entirely, supporting scientists who deliberately ship without lubricants. Ignored for powders / gummies.", related_name='anti_caking_formulations', to='catalogues.item', verbose_name='anti-caking items'),
        ),
    ]
