# Generated by Django 6.0.4 on 2026-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('formulations', '0027_formulation_anti_caking_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='powder_carrier_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the structural carrier on a powder formulation -- typically Maltodextrin, but any item tagged use_as in ('Carrier', 'Bulking Agent') is admissible. The carrier total fills the remainder of the sachet after the actives and the other excipient bands, mirroring the way scientists historically added Maltodextrin as a real actives line. Empty list = no carrier band on the formulation. Ignored for capsule, tablet, gummy, and liquid forms.", related_name='powder_carrier_formulations', to='catalogues.item', verbose_name='powder carrier items'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='anti_caking_items',
            field=models.ManyToManyField(blank=True, help_text="Raw-material items used as the combined anti-caking agent on a capsule, tablet, or powder (typically Magnesium Stearate + Silicon Dioxide, but any item tagged use_as = 'Anti-caking Agent' is admissible). Contribution is dynamic per pick: a silica-only pick fires the 0.4% silica band, a stearate-only pick the 1.0% lubricant band, and picking both lights up the full 1.4%. **Empty list = no anti-caking on the formulation at all** -- the spec sheet drops the row entirely, supporting scientists who deliberately ship without lubricants. Ignored for gummies.", related_name='anti_caking_formulations', to='catalogues.item', verbose_name='anti-caking items'),
        ),
    ]
