# Generated by Django 6.0.4 on 2026-05-12 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0028_formulation_powder_carrier_items_and_more'),
        ('organizations', '0007_membership_orgs_membership_org_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['organization', 'project_status'], name='formulations_org_status_idx'),
        ),
    ]
