# Generated by Django 6.0.4 on 2026-05-14 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0030_backfill_approved_version_from_specs'),
        ('organizations', '0011_membership_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['organization', 'sales_person'], name='formulations_org_sales_idx'),
        ),
    ]
