# Generated by Django 6.0.4 on 2026-05-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0031_formulation_formulations_org_sales_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='lead_scientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_scientist_formulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
