# Generated by Django 6.0.4 on 2026-05-22 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0032_formulation_lead_scientist'),
        ('organizations', '0014_backfill_proposals_view_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['organization', 'lead_scientist'], name='formulations_org_lead_sci_idx'),
        ),
    ]
