# Generated by Django 6.0.4 on 2026-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0033_formulation_formulations_org_lead_sci_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='is_rtg_published',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this Ready-to-Go recipe surfaces in the portal catalog for org customers. Only meaningful when ``project_type=ready_to_go``; the publish service refuses to flip this on for Custom projects.', verbose_name='published to RTG catalog'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit price used to pre-fill the drafted proposal line when a customer orders this SKU from the catalog. Currency is ``rtg_currency_code``.', max_digits=12, null=True, verbose_name='RTG base price'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_currency_code',
            field=models.CharField(default='GBP', help_text="ISO 4217 code for ``rtg_base_price``. Snapshotted onto the drafted proposal so the customer's quote never drifts against a later catalog re-price.", max_length=3, verbose_name='RTG currency code'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for the catalog card. Optional — the FE falls back to a monogram tile when unset.', null=True, upload_to='rtg-hero/', verbose_name='RTG hero image'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_moq',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest quantity the customer may order in one go. Enforced server-side at submission — the portal short form refuses to submit below this value.', null=True, verbose_name='RTG minimum order quantity'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_packaging_options',
            field=models.JSONField(blank=True, default=list, help_text='List of packaging variant labels the customer picks from at order time (e.g. ``["120g jar", "60-count pouch"]``). At least one entry required to publish. The submission service validates the chosen packaging against this list.', verbose_name='RTG packaging options'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_short_description',
            field=models.TextField(blank=True, default='', help_text='Marketing sub-copy shown on the catalog card (one to two sentences). Kept short so the grid stays scannable.', verbose_name='RTG short description'),
        ),
    ]
