# Generated by Django 6.0.4 on 2026-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0034_formulation_rtg_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='rtg_display_name',
            field=models.CharField(blank=True, default='', help_text='Customer-facing name shown on the RTG catalog (staff hub + portal grid + order confirmation). Kept separate from ``name`` so R&D can keep the internal identifier (``PROT-042 · Vanilla Protein v3.2``) untouched for specs + audit while marketing uses a cleaner label (``Signature Vanilla Whey``). Blank falls back to ``name`` in every consumer.', max_length=200, verbose_name='RTG display name'),
        ),
    ]
