# Generated by Django 6.0.4 on 2026-07-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0035_formulation_rtg_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationline',
            name='item_source',
            field=models.CharField(choices=[('local', 'Local catalogue'), ('psp', 'PSP catalogue')], db_index=True, default='local', max_length=16, verbose_name='item source'),
        ),
        migrations.AddField(
            model_name='formulationline',
            name='psp_item_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='PSP item snapshot'),
        ),
        migrations.AddField(
            model_name='formulationline',
            name='psp_item_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='PSP item UUID'),
        ),
        migrations.AlterField(
            model_name='formulationline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulation_lines', to='catalogues.item'),
        ),
    ]
