# Generated by Django 6.0.4 on 2026-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_item_psp_source_uuid'),
        ('formulations', '0036_formulationline_item_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='capsule_shell_items',
            field=models.ManyToManyField(blank=True, help_text="Empty capsule shell items the finished pack is filled into. Each pick must carry use_as = 'Capsule Shell'. The shell's attributes.capsule_size drives the fill capacity for compute; attributes.shell_weight_mg drives the mg the declaration attributes to the shell row. Empty list falls back to the hardcoded per-size table (CAPSULE_SHELL_WEIGHTS in the FE, matching constants on the Python side) so legacy formulations keep rendering. Ignored for tablet / powder / gummy.", related_name='capsule_shell_formulations', to='catalogues.item', verbose_name='capsule shell items'),
        ),
    ]
