# Generated by Django 6.0.4 on 2026-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0037_formulation_capsule_shell_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='psp_finished_product_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text="PSP integration item this formulation is the recipe for — populated when a scientist picks a finished product from the 'Pick from PSP catalogue' surface on new-project creation. On every ``save_version``, NPD translates the formulation's actives + excipient picks into a BOM payload and pushes it to PSP at ``PUT /api/integration/items/<uuid>/bom``, writing a fresh ``bom_version`` snapshot each save so PSP's history captures every R&D iteration. Nullable — formulations without a PSP link save + version normally, no push fires.", null=True, verbose_name='PSP finished product UUID'),
        ),
    ]
