# Generated by Django 6.0.4 on 2026-07-15 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0038_formulation_psp_finished_product_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('stage_key', models.CharField(choices=[('blend', 'Blend'), ('encapsulate', 'Encapsulate'), ('bottle', 'Bottle'), ('label', 'Label'), ('fill', 'Fill'), ('cook', 'Cook'), ('deposit', 'Deposit'), ('cure', 'Cure'), ('coat', 'Coat'), ('package', 'Package'), ('custom', 'Custom')], default='custom', max_length=32, verbose_name='stage key')),
                ('workstation_group_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='PSP workstation group UUID')),
                ('workstation_group_name', models.CharField(blank=True, default='', max_length=200, verbose_name='workstation group name (snapshot)')),
                ('setup_time_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='setup time (minutes)')),
                ('cycle_time_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cycle time (minutes)')),
                ('fixed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='fixed cost')),
                ('variable_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='variable cost')),
                ('psp_semi_finished_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='PSP semi-finished item UUID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'formulation stage',
                'verbose_name_plural': 'formulation stages',
                'ordering': ('formulation', 'sort_order'),
            },
        ),
        migrations.AddField(
            model_name='formulationline',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='formulations.formulationstage'),
        ),
        migrations.AddConstraint(
            model_name='formulationstage',
            constraint=models.UniqueConstraint(fields=('formulation', 'sort_order'), name='uniq_formulation_stage_sort_order'),
        ),
    ]
