# Generated by Django 6.0.4 on 2026-07-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0039_formulationstage_formulationline_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='operation_description',
            field=models.TextField(blank=True, default='', verbose_name='operation description'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='other_fixed_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='other fixed cost'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='other_variable_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='other variable cost'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='other_variable_cost_basis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='other variable cost basis'),
        ),
    ]
