# Generated by Django 6.0.4 on 2026-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0040_formulationstage_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='worker_psp_uuids',
            field=models.JSONField(blank=True, default=list, verbose_name='worker PSP UUIDs'),
        ),
    ]
