# Generated by Django 6.0.4 on 2026-07-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0041_formulationstage_worker_psp_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_description',
            field=models.TextField(blank=True, default='', verbose_name='PSP description'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_external_sku',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PSP external SKU'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_type',
            field=models.CharField(choices=[('semi_finished', 'Semi-finished'), ('finished_product', 'Finished product')], default='semi_finished', max_length=20, verbose_name='PSP item type'),
        ),
    ]
