# Generated by Django 6.0.4 on 2026-07-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0043_backfill_stage_psp_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='PSP item attributes'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_barcode',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='PSP barcode'),
        ),
    ]
