# Generated by Django 6.0.4 on 2026-07-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0044_formulationstage_psp_item_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_product_family_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='PSP product family UUID'),
        ),
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_stock_uom_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='PSP stock UOM UUID'),
        ),
    ]
