# Generated by Django 6.0.4 on 2026-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0045_formulationstage_psp_item_product_family_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_finished_product_spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='PSP finished-product spec'),
        ),
    ]
