# Generated by Django 6.0.4 on 2026-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0046_formulationstage_psp_finished_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='net_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='net quantity'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='net_quantity_uom_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='net quantity UOM UUID'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='regulatory_category',
            field=models.CharField(blank=True, choices=[('food_supplement', 'Food supplement'), ('functional_food', 'Functional food'), ('cosmetic', 'Cosmetic'), ('medical_device', 'Medical device')], default='', max_length=32, verbose_name='regulatory category'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='serving_size_uom_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='serving size UOM UUID'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='shelf_life_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='shelf life (months)'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='storage_conditions',
            field=models.TextField(blank=True, default='', verbose_name='storage conditions'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='target_markets',
            field=models.JSONField(blank=True, default=list, verbose_name='target markets'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='warnings_text',
            field=models.TextField(blank=True, default='', verbose_name='warnings text'),
        ),
    ]
