# Generated by Django 6.0.4 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0047_formulation_net_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='allergen_uuids',
            field=models.JSONField(blank=True, default=list, verbose_name='allergen UUIDs'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='may_contain_allergen_keys',
            field=models.JSONField(blank=True, default=list, verbose_name='may-contain allergen keys'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='may_contain_justification',
            field=models.TextField(blank=True, default='', verbose_name='may-contain justification'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='min_stock_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='min stock qty'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='storage_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='storage tags'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='target_stock_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='target stock qty'),
        ),
    ]
