# Generated by Django 6.0.4 on 2026-07-17 07:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0048_formulation_allergen_uuids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='formulation-files/', verbose_name='file')),
                ('kind', models.CharField(choices=[('spec_sheet', 'Spec sheet'), ('food_contact_declaration', 'Food-contact declaration'), ('migration_test', 'Migration test'), ('safety_data_sheet', 'Safety data sheet'), ('allergen_declaration', 'Allergen declaration'), ('nutritional_analysis', 'Nutritional analysis'), ('other', 'Other')], default='other', max_length=32, verbose_name='kind')),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=120)),
                ('byte_size', models.PositiveIntegerField()),
                ('psp_uuid', models.UUIDField(blank=True, help_text='UUID PSP returned when this file was first pushed to the finished-product item. Idempotency marker.', null=True, verbose_name='PSP item file UUID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='formulations.formulation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulation file',
                'verbose_name_plural': 'formulation files',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['formulation', '-uploaded_at'], name='formulation_formula_73eabd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormulationPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='formulation-photos/', verbose_name='image')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the hero shot used on catalog cards + label previews. Enforced single-primary in the service layer.', verbose_name='is primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('original_filename', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.CharField(blank=True, default='', max_length=80)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('psp_uuid', models.UUIDField(blank=True, help_text='UUID PSP returned when this photo was first pushed to the finished-product item. Idempotency marker — a non-null value means PSP already has it, so re-syncs skip re-uploading.', null=True, verbose_name='PSP item image UUID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='formulations.formulation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulation photo',
                'verbose_name_plural': 'formulation photos',
                'ordering': ('-is_primary', 'sort_order', 'uploaded_at'),
                'indexes': [models.Index(fields=['formulation', '-is_primary', 'sort_order'], name='formulation_formula_ce1f85_idx')],
            },
        ),
    ]
