# Generated by Django 6.0.4 on 2026-07-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0049_formulation_photos_and_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_item_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='PSP item name'),
        ),
    ]
