# Generated by Django 6.0.4 on 2026-07-20 13:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0050_formulationstage_psp_item_name'),
        ('organizations', '0016_organization_psp_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationStageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('description', models.TextField(blank=True, default='', help_text="Short human-readable summary shown next to the template in the picker (e.g. 'Standard 3-stage capsule route').", verbose_name='description')),
                ('dosage_form', models.CharField(blank=True, choices=[('powder', 'Powder'), ('capsule', 'Capsule'), ('tablet', 'Tablet'), ('gummy', 'Gummy'), ('liquid', 'Liquid'), ('other_solid', 'Other solid')], default='', max_length=32, verbose_name='dosage form hint')),
                ('stages_json', models.JSONField(blank=True, default=list, verbose_name='stages')),
                ('is_seeded', models.BooleanField(default=False, verbose_name='is seeded')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulation_stage_templates', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulation stage template',
                'verbose_name_plural': 'formulation stage templates',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='formulation_stage_template_unique_name_per_org')],
            },
        ),
    ]
