# Generated by Django 6.0.4 on 2026-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0053_formulationversion_snapshot_stage_boms'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationline',
            name='band_key',
            field=models.CharField(blank=True, choices=[('anti_caking', 'Anti-caking'), ('mcc', 'MCC carrier'), ('dcp', 'DCP carrier'), ('capsule_shell', 'Capsule shell'), ('flavouring', 'Flavouring'), ('colour', 'Colour'), ('sweetener', 'Sweetener'), ('gelling', 'Gelling agent'), ('glazing', 'Glazing'), ('acidity', 'Acidity regulator'), ('powder_carrier', 'Powder carrier'), ('gummy_base', 'Gummy base'), ('premix_sweetener', 'Premix sweetener')], db_index=True, max_length=32, null=True, verbose_name='band key'),
        ),
        migrations.AddField(
            model_name='formulationline',
            name='source_kind',
            field=models.CharField(choices=[('active', 'Operator-picked active ingredient'), ('band_pick', 'Compute-derived excipient / band pick')], db_index=True, default='active', max_length=16, verbose_name='source kind'),
        ),
    ]
