# Generated by Django 6.0.4 on 2026-07-21 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0054_formulationline_band_key_formulationline_source_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psp_certificate_uuid', models.UUIDField(verbose_name='PSP certificate UUID')),
                ('psp_certificate_name', models.CharField(max_length=200, verbose_name='certificate name')),
                ('psp_certificate_type', models.CharField(blank=True, default='', max_length=64, verbose_name='certificate type')),
                ('psp_issuing_body', models.CharField(blank=True, default='', max_length=200, verbose_name='issuing body')),
                ('certificate_number', models.CharField(blank=True, default='', max_length=200, verbose_name='certificate number')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('psp_attachment_uuid', models.UUIDField(blank=True, help_text='UUID PSP returned when this cert was first attached to the finished-product item. Idempotency marker.', null=True, verbose_name='PSP attachment UUID')),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'formulation certificate',
                'verbose_name_plural': 'formulation certificates',
                'ordering': ('psp_certificate_name',),
                'indexes': [models.Index(fields=['formulation'], name='formulation_formula_b59d22_idx')],
                'constraints': [models.UniqueConstraint(fields=('formulation', 'psp_certificate_uuid'), name='unique_formulation_certificate')],
            },
        ),
    ]
