# Generated by Django 6.0.4 on 2026-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0055_formulationcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulationline',
            name='source_kind',
            field=models.CharField(choices=[('active', 'Operator-picked active ingredient'), ('band_pick', 'Compute-derived excipient / band pick'), ('manual', 'Routing-tab manual pick')], db_index=True, default='active', max_length=16, verbose_name='source kind'),
        ),
    ]
