# Generated by Django 6.0.4 on 2026-07-22 07:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0056_alter_formulationline_source_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='servings_per_output_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='servings per output unit'),
        ),
    ]
