# Generated by Django 6.0.4 on 2026-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0057_formulationstage_servings_per_output_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationversion',
            name='is_auto',
            field=models.BooleanField(db_index=True, default=False, verbose_name='auto-cut on save draft'),
        ),
    ]
