# Generated by Django 6.0.4 on 2026-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0058_formulationversion_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationline',
            name='stage_ratio_mode',
            field=models.CharField(choices=[('none', 'No ratio (actives use label claim)'), ('per_unit', 'Per 1 output unit of stage'), ('percent_of_mass', '% of stage output mass')], default='none', max_length=24, verbose_name='stage ratio mode'),
        ),
        migrations.AddField(
            model_name='formulationline',
            name='stage_ratio_value',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="per_unit: qty in the item's UOM per 1 stage output unit. percent_of_mass: percentage (5 = 5%, not 0.05).", max_digits=14, null=True, verbose_name='stage ratio value'),
        ),
    ]
