# Generated by Django 6.0.4 on 2026-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0059_formulationline_stage_ratio_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationstage',
            name='psp_bom_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='PSP BOM UUID'),
        ),
    ]
