# Generated by Django 6.0.4 on 2026-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0060_formulationstage_psp_bom_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulationline',
            name='band_key',
            field=models.CharField(blank=True, choices=[('anti_caking', 'Anti-caking'), ('mcc', 'MCC carrier'), ('dcp', 'DCP carrier'), ('capsule_shell', 'Capsule shell'), ('flavouring', 'Flavouring'), ('colour', 'Colour'), ('sweetener', 'Sweetener'), ('gelling', 'Gelling agent'), ('glazing', 'Glazing'), ('acidity', 'Acidity regulator'), ('powder_carrier', 'Powder carrier'), ('gummy_base', 'Gummy base'), ('gummy_water', 'Gummy water'), ('premix_sweetener', 'Premix sweetener')], db_index=True, max_length=32, null=True, verbose_name='band key'),
        ),
    ]
