# Generated by Django 6.0.4 on 2026-07-23 19:45

from django.db import migrations, models


def backfill_is_complete(apps, schema_editor):
    """Backfill existing named versions to ``is_complete=True``.

    Pragmatic assumption: named ``Save version`` commits went through
    the FE gate (``spec_sheets_unlocked = builder_complete AND
    has_explicit_version``) so the operator wouldn't have been able to
    click Save version if the checklist wasn't clean. Auto-drafts
    stay False since they can fire on any keystroke-batch and don't
    represent a scientist commit worth showing on the spec picker.
    """
    FormulationVersion = apps.get_model("formulations", "FormulationVersion")
    FormulationVersion.objects.filter(is_auto=False).update(is_complete=True)


def reverse_noop(apps, schema_editor):
    """No inverse — dropping the column is what the schema migration
    reversal handles; leaving the data alone is fine."""


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0061_formulationline_gummy_water_band_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationversion',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='passed builder-readiness gate at save'),
        ),
        migrations.RunPython(backfill_is_complete, reverse_noop),
    ]
