# Generated by Django 6.0.4 on 2026-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0063_reset_version_is_complete_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationversion',
            name='snapshot_stages',
            field=models.JSONField(blank=True, default=list, verbose_name='stage graph snapshot'),
        ),
    ]
