# Generated by Django 6.0.4 on 2026-07-30 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_unique_email_per_org'),
        ('formulations', '0064_formulationversion_snapshot_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulations', to='customers.customer'),
        ),
    ]
