# Generated by Django 6.0.4 on 2026-08-01 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_item_regulatory_risk'),
        ('formulations', '0065_add_formulation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='rtg_packaging_options',
            field=models.JSONField(blank=True, default=list, help_text='Legacy free-text list of packaging labels. Superseded by :class:`PackagingCombo` — kept for backwards compat with already-published cards and the submission validator until Phase 2 migrates the portal picker to combos.', verbose_name='RTG packaging options'),
        ),
        migrations.CreateModel(
            name='PackagingCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Customer-facing combo label (e.g. "Bottle 60ct — premium"). Rendered on the catalog card + portal picker.', max_length=120, verbose_name='name')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Uplift applied on top of ``rtg_base_price`` when the customer picks this combo. Same currency as the RTG base.', max_digits=12, verbose_name='price delta')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending order combos render in on the picker. Editor renumbers on drag.', verbose_name='sort order')),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected in the portal picker when the customer lands on the product page. At most one per formulation.', verbose_name='default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_combos', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'packaging combo',
                'verbose_name_plural': 'packaging combos',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PackagingComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this item consumed per unit sold.', verbose_name='quantity')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formulations.packagingcombo')),
                ('item', models.ForeignKey(help_text="Packaging SKU from the catalogue. PROTECT because deleting an item that's referenced by a customer's chosen combo would silently break the audit trail on that order.", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogues.item')),
            ],
            options={
                'verbose_name': 'packaging combo item',
                'verbose_name_plural': 'packaging combo items',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='packagingcombo',
            constraint=models.UniqueConstraint(fields=('formulation', 'name'), name='packaging_combo_unique_name_per_formulation'),
        ),
        migrations.AddConstraint(
            model_name='packagingcomboitem',
            constraint=models.UniqueConstraint(fields=('combo', 'item'), name='packaging_combo_item_unique_per_combo'),
        ),
    ]
