# Generated by Django 6.0.4 on 2026-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0066_alter_formulation_rtg_packaging_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='rtg_long_description',
            field=models.TextField(blank=True, default='', help_text="Full-length catalog page body — authored in the staff rich-text editor, stored as sanitized HTML. Rendered on the customer portal's product page below the pricing row. Sanitized on save via ``bleach`` so a compromised session can't inject scripts.", verbose_name='RTG long description (rich HTML)'),
        ),
    ]
