# Generated by Django 6.0.4 on 2026-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0067_formulation_rtg_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='rtg_page_content',
            field=models.JSONField(blank=True, default=None, help_text="Structured page layout authored in the visual page builder (@puckeditor/core). Stored as JSON — safer than raw HTML because the render walks a fixed component schema so there's no XSS surface. When set, the portal renders this over ``rtg_long_description``.", null=True, verbose_name='RTG page content (Puck schema)'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='rtg_long_description',
            field=models.TextField(blank=True, default='', help_text='Legacy sanitized-HTML content authored in the standalone TipTap editor. Superseded by ``rtg_page_content`` (the Puck-authored page schema); kept as a graceful fallback so pre-migration catalog listings keep rendering.', verbose_name='RTG long description (rich HTML)'),
        ),
    ]
