# Generated by Django 6.0.4 on 2026-08-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0070_packagingcombo_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='rtg_sample_description',
            field=models.TextField(blank=True, default='', help_text="Plain-text description of what the customer receives in a sample — e.g. '3 sealed units in a labelled kit, no outer packaging'. Rendered next to the sample price on the product detail page so buyers know exactly what to expect before requesting.", verbose_name='RTG sample description'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_sample_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-sample cost shown next to the base price on the storefront. Charged separately from ``rtg_base_price`` — sampling is a distinct transaction that lets a customer evaluate the product before committing to an MOQ order. Currency inherits ``rtg_currency_code``.', max_digits=10, null=True, verbose_name='RTG sample price'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='rtg_slug',
            field=models.SlugField(blank=True, help_text="URL-safe identifier for the marketing site's product detail page (``/products/ready-to-go/<slug>``). Auto-generated from ``rtg_display_name`` on first publish. Once assigned it never rotates automatically — a rename keeps the slug so external links + SEO don't rot. Staff can override it manually if a URL must change; the ``unique`` constraint prevents collisions. Nullable so unpublished / non-RTG formulations don't collide on an empty-string default.", max_length=180, null=True, unique=True, verbose_name='RTG slug'),
        ),
        migrations.AlterField(
            model_name='formulationphoto',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Marks the hero shot for this photo's ``purpose`` scope. Enforced single-primary per (formulation, purpose) in the service layer.", verbose_name='is primary'),
        ),
        migrations.AlterField(
            model_name='packagingcombo',
            name='stage',
            field=models.ForeignKey(blank=True, help_text="Stage that will assemble this combo's packaging on the customer's PO. Required on RTG projects before Builder can advance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_combos', to='formulations.formulationstage'),
        ),
    ]
