# Generated by Django 6.0.4 on 2026-08-06 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_self_registration'),
        ('customers', '0006_customer_unique_email_per_org'),
        ('formulations', '0072_rtg_slug_backfill'),
        ('organizations', '0017_backfill_manage_stage_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('order', 'Order'), ('sample', 'Sample')], db_index=True, default='order', max_length=16, verbose_name='kind')),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=24, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units. For ``kind=order`` must be ≥ the snapshotted ``moq``; the service layer enforces this. For ``kind=sample`` the value is 1 — the sample cost already covers whatever kit staff defines.', verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="Snapshotted per-unit price at order time. For samples this is the sample_price from the RTG. Locked in — future catalogue re-pricing doesn't affect this order.", max_digits=12, verbose_name='unit price')),
                ('currency_code', models.CharField(default='GBP', help_text='ISO 4217. Snapshotted from the RTG at order time.', max_length=3, verbose_name='currency code')),
                ('moq_snapshot', models.PositiveIntegerField(blank=True, help_text="The Formulation's MOQ at the moment this order was placed. Kept for audit — later MOQ changes don't affect already-placed orders.", null=True, verbose_name='MOQ snapshot')),
                ('delivery_address', models.TextField(blank=True, default='', help_text='Free-text ship-to address. Kept as a single blob rather than structured fields until we have a real logistics layer — every downstream consumer just needs to render or print it.', verbose_name='delivery address')),
                ('notes', models.TextField(blank=True, default='', help_text='Anything the customer wants staff to see: special delivery windows, expected launch date, label-approval sequencing. Not visible to production ops until staff reviews the order.', verbose_name='customer notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_account', models.ForeignKey(blank=True, help_text="The portal login that submitted the order. Nullable so an account deactivation doesn't cascade-delete the history — the ``customer`` FK still anchors ownership.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_portal.clientaccount')),
                ('customer', models.ForeignKey(help_text='The CRM row for the buyer. PROTECT because customer deletion should not silently orphan an order in the middle of the production chain.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customers.customer')),
                ('formulation', models.ForeignKey(help_text="The published RTG SKU being ordered. PROTECT so a catalog rework can't nuke an in-flight order — staff must unpublish + reconcile explicitly.", on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='formulations.formulation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='organizations.organization')),
                ('packaging_combo', models.ForeignKey(blank=True, help_text='Which packaging combo the customer selected on the storefront. NULL for samples (fixed sample kit) or for SKUs published before the combo picker landed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='formulations.packagingcombo')),
            ],
            options={
                'verbose_name': 'customer order',
                'verbose_name_plural': 'customer orders',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='formulation_organiz_8f4388_idx'), models.Index(fields=['customer', '-created_at'], name='formulation_custome_3bb140_idx')],
            },
        ),
    ]
