# Generated by Django 6.0.4 on 2026-08-07 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0073_customer_order'),
        ('organizations', '0017_backfill_manage_stage_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBuilderTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('description', models.TextField(blank=True, default='', help_text="Short summary shown under the template name in the picker (e.g. 'Supplement long-form product page with ingredient breakdown + trust rail').", verbose_name='description')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_builder_templates', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page-builder template',
                'verbose_name_plural': 'page-builder templates',
                'ordering': ('-is_default', 'name'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='page_builder_template_unique_name_per_org'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='page_builder_template_single_default')],
            },
        ),
    ]
