# Generated by Django 6.0.4 on 2026-09-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0076_packagingcomboitem_stage'),
        ('specifications', '0018_specificationsheet_customer_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='is_reorder',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this formulation was created by the portal Reorder flow. Drives the RTG-style independent-CO merge on PSP and the ``<source> Reorder <n>`` naming.', verbose_name='is reorder'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='reorder_original_spec',
            field=models.ForeignKey(blank=True, help_text="Provenance pointer to the source formulation's signed FINAL spec. Audit-only — the actual reuse happens via ``ProposalLine.specification_sheet`` pointing at the same row.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specifications.specificationsheet'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='reorder_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='1-based counter of reorders on the source formulation. Composes into the display name (`<source> Reorder <n>`). NULL on non-reorder rows.', null=True, verbose_name='reorder sequence'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='source_formulation',
            field=models.ForeignKey(blank=True, help_text="The original Custom formulation this row is a reorder of. Nullable so deleting the source doesn't cascade the reorder away — the reorder is a self-contained order at that point.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorders', to='formulations.formulation'),
        ),
    ]
