# Generated by Django 6.0.4 on 2026-04-18 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_permissions_to_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=32, verbose_name='provider')),
                ('model', models.CharField(max_length=128, verbose_name='model')),
                ('purpose', models.CharField(choices=[('formulation_draft', 'Formulation draft')], max_length=64, verbose_name='purpose')),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Tokens counted by the provider, if reported.', null=True, verbose_name='prompt tokens')),
                ('completion_tokens', models.IntegerField(blank=True, null=True, verbose_name='completion tokens')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='latency (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='error code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage',
                'verbose_name_plural': 'AI usage entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='ai_aiusage_organiz_1f333f_idx'), models.Index(fields=['provider', 'model'], name='ai_aiusage_provide_f63141_idx'), models.Index(fields=['purpose'], name='ai_aiusage_purpose_3742aa_idx')],
            },
        ),
    ]
