# Generated by Django 6.0.4 on 2026-04-17 16:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitation'),
        ('trial_batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_test', models.JSONField(blank=True, default=dict, help_text='``{target_mg, tolerance_pct, samples: [mg, ...], notes}``. Stats (mean, stdev, pass/fail) are computed on read.', verbose_name='weight test')),
                ('hardness_test', models.JSONField(blank=True, default=dict, help_text='``{target_min_n, target_max_n, samples: [N, ...], notes}``. Tablet-only; capsules leave this untouched.', verbose_name='hardness test')),
                ('thickness_test', models.JSONField(blank=True, default=dict, help_text='``{target_mm, tolerance_mm, samples: [mm, ...], notes}``. Tablet-only; capsules leave this untouched.', verbose_name='thickness test')),
                ('disintegration_test', models.JSONField(blank=True, default=dict, help_text='``{limit_minutes, temperature_c, samples: [minutes, ...], notes}``. The worst-case sample drives pass/fail.', verbose_name='disintegration test')),
                ('organoleptic_test', models.JSONField(blank=True, default=dict, help_text='``{target: {colour, taste, odour}, actual: {colour, taste, odour}, passed, notes}``. Subjective, so pass/fail is recorded by the scientist rather than derived.', verbose_name='organoleptic test')),
                ('mrpeasy_checklist', models.JSONField(blank=True, default=dict, help_text="``{raw_materials_created, finished_product_created, boms_verified}``. Booleans the scientist ticks once the batch's BOM has been wired into the ERP.", verbose_name='MRPeasy checklist')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='draft', max_length=16, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('scientist_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='scientist signed at')),
                ('rd_manager_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='R&D manager signed at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_validations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_validations', to='organizations.organization')),
                ('rd_manager_signature', models.ForeignKey(blank=True, help_text="Stamped when the validation reaches ``passed`` or ``failed`` — the manager's sign-off is what releases or rejects the batch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_validations_as_rd_manager', to=settings.AUTH_USER_MODEL)),
                ('scientist_signature', models.ForeignKey(blank=True, help_text='Stamped when the validation moves past ``draft``. Records *who* ran the QC, not just that QC ran.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_validations_as_scientist', to=settings.AUTH_USER_MODEL)),
                ('trial_batch', models.OneToOneField(help_text='One validation per batch. Deleting the batch cascades — the QC record is meaningless once the physical run it documents is gone.', on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='trial_batches.trialbatch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_product_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product validation',
                'verbose_name_plural': 'product validations',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='product_val_organiz_27415d_idx'), models.Index(fields=['organization', '-updated_at'], name='product_val_organiz_480278_idx')],
            },
        ),
    ]
