# Generated by Django 6.0.4 on 2026-04-17 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0004_backfill_snapshot_anticaking_grouping'),
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='Optional human-readable name — e.g. ``Pilot run 2026-04-17`` or ``First production lot``.', max_length=200, verbose_name='label')),
                ('batch_size_units', models.PositiveIntegerField(help_text='Number of finished product units (capsules, tablets, bottles, pouches...) the batch will produce. Drives the scale-up math.', verbose_name='batch size (units)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trial_batches', to=settings.AUTH_USER_MODEL)),
                ('formulation_version', models.ForeignKey(help_text="Immutable snapshot the batch scales against. Editing the underlying formulation never rewrites this batch's BOM.", on_delete=django.db.models.deletion.PROTECT, related_name='trial_batches', to='formulations.formulationversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_batches', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_trial_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trial batch',
                'verbose_name_plural': 'trial batches',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='trial_batch_organiz_bf3990_idx'), models.Index(fields=['formulation_version', '-created_at'], name='trial_batch_formula_dd07d3_idx')],
            },
        ),
    ]
