# Generated by Django 6.0.4 on 2026-08-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_batches', '0003_trialbatch_psp_manufacturing_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbatch',
            name='psp_all_stages_completed',
            field=models.BooleanField(default=False, help_text='Cached: every stage MO in the PSP chain has ``status = completed``. Drives the QC tab gate.'),
        ),
        migrations.AlterField(
            model_name='trialbatch',
            name='psp_manufacturing_order_uuid',
            field=models.UUIDField(blank=True, help_text='Cross-system handle for the PSP Manufacturing Order this trial batch spawned.', null=True),
        ),
    ]
