# Generated by Django 6.0.4 on 2026-08-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0074_page_builder_template'),
        ('payments', '0006_payment_customer'),
        ('trial_batches', '0006_trialbatch_packaging_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbatch',
            name='source_payment',
            field=models.ForeignKey(blank=True, help_text='Sample Payment this batch fulfils. NULL for batches started from the per-project trial-batches tab (no payment context); populated when the batch is created from the R&D Samples fulfilment queue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_by_trial_batches', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='trialbatch',
            name='packaging_combo',
            field=models.ForeignKey(blank=True, help_text="Optional packaging overlay for sample batches. NULL = no combo picked (loose-bulk output or trial-kind bench run); populated = the PSP MO's packaging BOM lines are replaced by the combo's items at MO-create time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_batches', to='formulations.packagingcombo'),
        ),
    ]
