# Generated by Django 6.0.4 on 2026-08-20 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_self_registration'),
        ('formulations', '0074_page_builder_template'),
        ('organizations', '0019_backfill_sample_pricing'),
        ('payments', '0010_alter_payment_kind'),
        ('trial_batches', '0007_trial_batch_source_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBatchCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('satisfied', 'Satisfied'), ('terminated_by_team', 'Terminated by team'), ('max_reached', 'Max reached')], default='in_progress', max_length=32, verbose_name='status')),
                ('total_slots', models.PositiveIntegerField(default=0, verbose_name='total slots')),
                ('terminated_reason', models.TextField(blank=True, default='', verbose_name='termination reason')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.OneToOneField(help_text='The custom-formulation project this cycle is producing samples against. OneToOne because a formulation only ever has one active trial-batch cycle at a time — additional samples extend the same cycle rather than starting a fresh one.', on_delete=django.db.models.deletion.CASCADE, related_name='trial_batch_cycle', to='formulations.formulation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_batch_cycles', to='organizations.organization')),
                ('sample_allocation', models.ForeignKey(help_text="The customer's post-proposal sample-count pick. Seed for ``total_slots`` at creation time.", on_delete=django.db.models.deletion.PROTECT, related_name='trial_batch_cycles', to='payments.sampleallocation')),
                ('seed_payment', models.ForeignKey(help_text='The bundled deposit+samples Payment whose approval spawned this cycle.', on_delete=django.db.models.deletion.PROTECT, related_name='seeded_trial_batch_cycles', to='payments.payment')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trial-batch cycle',
                'verbose_name_plural': 'trial-batch cycles',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalSampleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='requested quantity')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='unit price snapshot')),
                ('currency_code', models.CharField(default='GBP', max_length=3, verbose_name='currency code')),
                ('total_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total amount snapshot')),
                ('status', models.CharField(choices=[('awaiting_finance', 'Awaiting finance approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_finance', max_length=32, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_sample_request', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='client_portal.clientaccount')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_sample_requests', to='trial_batches.trialbatchcycle')),
            ],
            options={
                'verbose_name': 'additional-sample request',
                'verbose_name_plural': 'additional-sample requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrialBatchSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField(verbose_name='sequence number')),
                ('status', models.CharField(choices=[('awaiting_scientist', 'Awaiting scientist'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('feedback_pending', 'Feedback pending'), ('closed_iterated', 'Closed — iterating'), ('closed_satisfied', 'Closed — satisfied'), ('closed_cancelled', 'Closed — cancelled')], default='awaiting_scientist', max_length=32, verbose_name='status')),
                ('verdict', models.CharField(blank=True, choices=[('needs_iteration', 'Needs iteration'), ('satisfied', 'Satisfied')], max_length=32, null=True, verbose_name='verdict')),
                ('verdict_at', models.DateTimeField(blank=True, null=True, verbose_name='verdict at')),
                ('keep_producing_remaining', models.BooleanField(default=False, verbose_name='keep producing remaining slots')),
                ('feedback_summary', models.TextField(blank=True, default='', verbose_name='feedback summary')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='trial_batches.trialbatchcycle')),
                ('formulation_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='formulations.formulationversion')),
                ('trial_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_slot', to='trial_batches.trialbatch')),
            ],
            options={
                'verbose_name': 'trial-batch slot',
                'verbose_name_plural': 'trial-batch slots',
                'ordering': ('cycle', 'sequence_no'),
            },
        ),
        migrations.AddIndex(
            model_name='trialbatchcycle',
            index=models.Index(fields=['organization', '-updated_at'], name='trial_batch_organiz_f23171_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbatchcycle',
            index=models.Index(fields=['status'], name='trial_batch_status_4fcfef_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalsamplerequest',
            index=models.Index(fields=['cycle', 'status'], name='trial_batch_cycle_i_3280b3_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbatchslot',
            index=models.Index(fields=['cycle', 'status'], name='trial_batch_cycle_i_78ba07_idx'),
        ),
        migrations.AddConstraint(
            model_name='trialbatchslot',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence_no'), name='trial_batch_slot_unique_per_cycle'),
        ),
    ]
