# Generated by Django 6.0.4 on 2026-08-25 06:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0074_page_builder_template'),
        ('psp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PspProductionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psp_customer_order_uuid', models.UUIDField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, default='', max_length=48)),
                ('phase_label', models.CharField(blank=True, default='', max_length=120)),
                ('next_action_title', models.CharField(blank=True, default='', max_length=200)),
                ('next_action_detail', models.TextField(blank=True, default='')),
                ('blocker_count', models.PositiveIntegerField(default=0)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('mo_count', models.PositiveIntegerField(default=0)),
                ('lines_awaiting_mo', models.PositiveIntegerField(default=0)),
                ('mos_awaiting_po_send', models.PositiveIntegerField(default=0)),
                ('mos_awaiting_delivery', models.PositiveIntegerField(default=0)),
                ('mos_in_production', models.PositiveIntegerField(default=0)),
                ('mos_awaiting_closeout', models.PositiveIntegerField(default=0)),
                ('psp_updated_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psp_production_status', to='formulations.formulation')),
            ],
            options={
                'verbose_name': 'PSP production status',
                'verbose_name_plural': 'PSP production statuses',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['phase'], name='psp_pspprod_phase_098aad_idx'), models.Index(fields=['-updated_at'], name='psp_pspprod_updated_6837a7_idx')],
            },
        ),
    ]
