# Generated by Django 6.0.4 on 2026-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp', '0002_pspproductionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspproductionstatus',
            name='manufacturing_orders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
