# Generated by Django 6.0.4 on 2026-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp', '0003_pspproductionstatus_manufacturing_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspproductionstatus',
            name='routing_request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
