# Generated by Django 6.0.4 on 2026-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp', '0004_add_routing_request_to_psp_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspproductionstatus',
            name='dispatch_progress',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
