# Generated by Django 6.0.4 on 2026-04-16 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0001_initial'),
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Sheet reference code. Optional, unique per org when set.', max_length=64, verbose_name='code')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='client name')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='client email')),
                ('client_company', models.CharField(blank=True, default='', max_length=200, verbose_name='client company')),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional target margin for the quote.', max_digits=6, null=True, verbose_name='margin %')),
                ('final_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='final price')),
                ('cover_notes', models.TextField(blank=True, default='', verbose_name='cover notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_specification_sheets', to=settings.AUTH_USER_MODEL)),
                ('formulation_version', models.ForeignKey(help_text='Immutable snapshot the sheet renders against. Editing the underlying formulation never rewrites this sheet.', on_delete=django.db.models.deletion.PROTECT, related_name='specification_sheets', to='formulations.formulationversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_sheets', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_specification_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'specification sheet',
                'verbose_name_plural': 'specification sheets',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='specificati_organiz_81a7ef_idx'), models.Index(fields=['organization', '-updated_at'], name='specificati_organiz_6c0495_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='specifications_unique_code_per_org')],
            },
        ),
    ]
