# Generated by Django 6.0.4 on 2026-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='total_weight_label',
            field=models.CharField(blank=True, default='', help_text="Free-text override for the spec sheet's Total Weight (mg) row. Blank renders as ``TBC`` to match the workbook's convention — the filled-capsule weight depends on the physical shell delivered by the manufacturer and is set by hand once known.", max_length=64, verbose_name='total weight label'),
        ),
    ]
