# Generated by Django 6.0.4 on 2026-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_specificationsheet_total_weight_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, default=None, help_text='Opaque UUID that, when set, grants unauthenticated read-only access to this sheet via the public preview URL. Null by default — sheets are private unless a link is explicitly generated. Rotating the token invalidates every previously-shared link in one write.', null=True, unique=True, verbose_name='public token'),
        ),
    ]
