# Generated by Django 6.0.4 on 2026-04-17 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0003_specificationsheet_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Status the sheet left. Recorded alongside ``to_status`` so the audit trail is readable in isolation, without joining against the previous transition row.', max_length=16, verbose_name='from status')),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=16, verbose_name='to status')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional free-text justification the actor left at transition time — e.g. ``approved pending pack change``.', verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_transitions', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='specifications.specificationsheet')),
            ],
            options={
                'verbose_name': 'specification transition',
                'verbose_name_plural': 'specification transitions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sheet', '-created_at'], name='specificati_sheet_i_202b12_idx')],
            },
        ),
    ]
