# Generated by Django 6.0.4 on 2026-04-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('specifications', '0004_specificationtransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='packaging_antitemper',
            field=models.ForeignKey(blank=True, help_text="Tamper-evidence component from the packaging catalogue. Renders on the spec sheet's Antitemper row.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_sheets_as_antitemper', to='catalogues.item'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='packaging_container',
            field=models.ForeignKey(blank=True, help_text="Primary container (bottle, pouch, tub) from the packaging catalogue. Renders on the spec sheet's Bottle/Pouch/Tub row.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_sheets_as_container', to='catalogues.item'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='packaging_label',
            field=models.ForeignKey(blank=True, help_text="Product label from the packaging catalogue. Renders on the spec sheet's Label Size row.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_sheets_as_label', to='catalogues.item'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='packaging_lid',
            field=models.ForeignKey(blank=True, help_text="Closure / lid from the org's packaging catalogue. Renders on the spec sheet's Lid Description row.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_sheets_as_lid', to='catalogues.item'),
        ),
    ]
