# Generated by Django 6.0.4 on 2026-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0005_specificationsheet_packaging_antitemper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='food_contact_status',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='food contact status'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='limits_override',
            field=models.JSONField(blank=True, default=dict, help_text="Per-sheet overrides for the Microbiological / PAH / Pesticides / Heavy Metal block. Keys match the canonical slug list (``total_aerobic``, ``total_yeast``, ``e_coli``, ``salmonella``, ``pah``, ``heavy_metal``, ``pesticides``, ``others``); values are free-text limit strings. Empty dict means fall back to the organization's ``default_limits``.", verbose_name='limits override'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='section_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Map of section-slug → bool that decides which blocks the customer-facing sheet renders. Absence of a key is interpreted as ``True`` so existing sheets keep showing everything; toggling a section off writes ``False`` here. The ``manage_spec_visibility`` capability gates writes.', verbose_name='section visibility'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='shelf_life',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='shelf life'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='storage_conditions',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='storage conditions'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='unit_quantity',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='unit quantity'),
        ),
    ]
