# Generated by Django 6.0.4 on 2026-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0006_specificationsheet_food_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='section_order',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of section slugs that overrides the default top-down layout of the customer-facing sheet. Missing or unknown slugs fall back to the canonical order, so a stale override cannot hide a newly-added section. Gated by the same ``manage_spec_visibility`` capability as the on/off toggles.', verbose_name='section order'),
        ),
    ]
