# Generated by Django 6.0.4 on 2026-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0009_specificationsheet_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='document_kind',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', help_text='Whether this sheet prints as a working draft (with the diagonal DRAFT watermark) or as a final document (clean). Independent of ``status`` — scientists flip it explicitly so an internal draft can circulate with the watermark even on an ``approved`` sheet, and vice versa.', max_length=16, verbose_name='document kind'),
        ),
    ]
