# Generated by Django 6.0.4 on 2026-05-12 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0029_formulation_formulations_org_status_idx'),
        ('organizations', '0007_membership_orgs_membership_org_idx'),
        ('specifications', '0011_specificationsheet_snapshot_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specificationsheet',
            index=models.Index(fields=['formulation_version'], name='specs_formulation_version_idx'),
        ),
    ]
