# Generated by Django 6.0.4 on 2026-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0012_specificationsheet_specs_formulation_version_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='customer_sign_document_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hex digest of the rendered HTML the customer saw at sign time. Lets us detect post-sign drift.', max_length=64, verbose_name='customer sign document hash'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='customer_sign_ip',
            field=models.CharField(blank=True, default='', help_text='Source IP recorded at kiosk sign time. IPv6 fits in 45 chars.', max_length=45, verbose_name='customer sign ip'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='customer_sign_user_agent',
            field=models.TextField(blank=True, default='', help_text='Raw User-Agent header recorded at kiosk sign time.', verbose_name='customer sign user agent'),
        ),
    ]
