# Generated by Django 6.0.4 on 2026-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0014_clear_legacy_document_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='currency',
            field=models.CharField(default='GBP', help_text='ISO-4217 currency code. Defaults to GBP; override per spec when quoting in another currency.', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units in the order this price quotes. The proposal modal seeds its own ``quantity`` from this value when the spec is selected.', verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='What the unit costs us to make. Combined with ``margin_percent`` to compute the customer unit price (stored on ``final_price``).', max_digits=12, null=True, verbose_name='unit cost'),
        ),
    ]
