# Generated by Django 6.0.4 on 2026-05-14 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_item_catalogues_item_list_idx'),
        ('formulations', '0031_formulation_formulations_org_sales_idx'),
        ('organizations', '0011_membership_groups'),
        ('specifications', '0015_specificationsheet_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specificationsheet',
            index=models.Index(fields=['formulation_version', 'document_kind', 'status'], name='specs_fv_kind_status_idx'),
        ),
    ]
