# Generated by Django 6.0.4 on 2026-07-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0016_specificationsheet_specs_fv_kind_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsheet',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp at which the sheet was moved to ``sent`` and the delivery evidence was captured. Null on any sheet that has never left ``approved``.', null=True, verbose_name='sent at'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='sent_delivery_method',
            field=models.CharField(blank=True, choices=[('public_link', 'Public preview link'), ('email', 'Email'), ('other', 'Other')], default='', help_text='How the customer received the sheet: the auto-generated public preview link, an email attachment, or a manual channel (courier / in-person / etc.). Captured at the ``approved → sent`` transition; empty until then.', max_length=16, verbose_name='sent delivery method'),
        ),
        migrations.AddField(
            model_name='specificationsheet',
            name='sent_recipient',
            field=models.CharField(blank=True, default='', help_text='Recipient identifier for the sent delivery — an email address for the ``email`` channel, a free-text note (e.g. ``courier: Sarah at DHL``) for ``other``, or the public preview URL for ``public_link``. Frozen at the ``approved → sent`` transition; empty on any sheet still in earlier states.', max_length=200, verbose_name='sent recipient'),
        ),
    ]
