# Generated by Django 6.0.4 on 2026-04-23 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0014_alter_formulation_approved_version_number_and_more'),
        ('organizations', '0005_organization_default_spec_limits'),
        ('specifications', '0009_specificationsheet_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Proposal reference code (e.g. ``PROP-0001``).', max_length=64, verbose_name='code')),
                ('template_type', models.CharField(choices=[('custom', 'Custom'), ('ready_to_go', 'Ready to Go')], default='custom', max_length=16, verbose_name='template type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=16, verbose_name='status')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='customer name')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=60, verbose_name='customer phone')),
                ('customer_company', models.CharField(blank=True, default='', max_length=200, verbose_name='customer company')),
                ('invoice_address', models.TextField(blank=True, default='', verbose_name='invoice address')),
                ('delivery_address', models.TextField(blank=True, default='', verbose_name='delivery address')),
                ('dear_name', models.CharField(blank=True, default='', help_text='Appears on the ``Dear <name>,`` greeting. Defaults to the customer name; scientists can override for formal salutations.', max_length=200, verbose_name='dear name')),
                ('reference', models.CharField(blank=True, default='', help_text="Free-text reference printed on the ``Ref:`` line of the proposal. Typically an internal quote id or the client's PO number.", max_length=120, verbose_name='reference')),
                ('currency', models.CharField(default='GBP', help_text='ISO 4217 code. Proposals only support one currency per document.', max_length=3, verbose_name='currency')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of finished packs (bottles/pouches/tubs) the client is ordering.', verbose_name='quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='unit price')),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Freight charge (Ready to Go only — Custom quotes bundle it into the unit price). Blank leaves the freight row off the rendered proposal.', max_digits=12, null=True, verbose_name='freight amount')),
                ('material_cost_per_pack', models.DecimalField(blank=True, decimal_places=4, help_text='Computed from raw-material ``cost_price_per_kg`` × mg-per-pack at creation. Informational — the unit price the client pays is edited separately.', max_digits=12, null=True, verbose_name='material cost per pack')),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Target margin the scientist picked when creating the proposal. Drives the auto-suggested unit price.', max_digits=6, null=True, verbose_name='margin %')),
                ('cover_notes', models.TextField(blank=True, default='', verbose_name='cover notes')),
                ('valid_until', models.DateField(blank=True, help_text='Offer validity date. The workbook template defaults to 14 days from issue — pre-filled on create but editable.', null=True, verbose_name='valid until')),
                ('prepared_by_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='prepared-by signed at')),
                ('prepared_by_signature_image', models.TextField(blank=True, default='', verbose_name='prepared-by signature image')),
                ('director_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='director signed at')),
                ('director_signature_image', models.TextField(blank=True, default='', verbose_name='director signature image')),
                ('customer_signer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='customer signer name')),
                ('customer_signer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='customer signer email')),
                ('customer_signer_company', models.CharField(blank=True, default='', max_length=200, verbose_name='customer signer company')),
                ('customer_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='customer signed at')),
                ('customer_signature_image', models.TextField(blank=True, default='', verbose_name='customer signature image')),
                ('public_token', models.UUIDField(blank=True, db_index=True, default=None, help_text="Opaque UUID that grants unauthenticated read-only access to this proposal via the public preview URL. When a specification_sheet is attached, the sheet's token is the primary entry point and this one can stay null.", null=True, unique=True, verbose_name='public token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('director_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_proposals', to=settings.AUTH_USER_MODEL)),
                ('formulation_version', models.ForeignKey(help_text='Immutable snapshot the proposal pins against. Editing the underlying formulation never rewrites a sent proposal.', on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='formulations.formulationversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='organizations.organization')),
                ('prepared_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_proposals', to=settings.AUTH_USER_MODEL)),
                ('specification_sheet', models.OneToOneField(blank=True, help_text="Optional link to the spec sheet this proposal accompanies. When set, the kiosk page renders both documents together and the customer's single accept-and-sign action marks both ``ACCEPTED`` at the same time.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='specifications.specificationsheet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_transitions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'proposal status transition',
                'verbose_name_plural': 'proposal status transitions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'status'], name='proposals_p_organiz_b9a34a_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', '-updated_at'], name='proposals_p_organiz_88c01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='proposals_unique_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='proposalstatustransition',
            index=models.Index(fields=['proposal', '-created_at'], name='proposals_p_proposa_123ba7_idx'),
        ),
    ]
