# Generated by Django 6.0.4 on 2026-04-23 10:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0014_alter_formulation_approved_version_number_and_more'),
        ('proposals', '0001_initial'),
        ('specifications', '0009_specificationsheet_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, default='', max_length=200, verbose_name='product code')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='What it costs Vita NPD to produce one pack of this line. Informational — the margin percentage is derived from this number and ``unit_price``.', max_digits=12, null=True, verbose_name='unit cost')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='unit price')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort key the rendered proposal uses to order lines in the pricing table. Scientists drag to reorder; zeroes break ties by ``created_at``.', verbose_name='display order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation_version', models.ForeignKey(blank=True, help_text="Frozen formulation snapshot this line quotes. Nullable so a scientist can add a free-text ad-hoc line (e.g. 'Shipping crate') that does not correspond to a project.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_lines', to='formulations.formulationversion')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='proposals.proposal')),
                ('specification_sheet', models.ForeignKey(blank=True, help_text="Optional link to the spec sheet for this line's product. When set, the kiosk renders the spec sheet inside the bundled signing flow. One proposal can bundle multiple spec sheets — one per line.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_lines', to='specifications.specificationsheet')),
            ],
            options={
                'verbose_name': 'proposal line',
                'verbose_name_plural': 'proposal lines',
                'ordering': ('display_order', 'created_at'),
                'indexes': [models.Index(fields=['proposal', 'display_order'], name='proposals_p_proposa_d0084d_idx')],
            },
        ),
    ]
