# Generated by Django 6.0.4 on 2026-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_backfill_proposal_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='rendered_pdf',
            field=models.BinaryField(blank=True, help_text='Cached PDF bytes of the most recent render. Invalidated whenever ``rendered_pdf_digest`` no longer matches the current proposal state.', null=True, verbose_name='rendered pdf'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rendered_pdf_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='rendered pdf digest'),
        ),
    ]
