# Generated by Django 6.0.4 on 2026-04-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('proposals', '0004_proposal_rendered_pdf_proposal_rendered_pdf_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="Optional link to the org's customer record so the same client is searchable across proposals. When set, the proposal's ``customer_*`` fields are seeded from the customer's address-book entry on create; scientists can still override any field per-proposal without losing the link.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='customers.customer'),
        ),
    ]
