# Generated by Django 6.0.4 on 2026-04-23 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='sales_person',
            field=models.ForeignKey(blank=True, help_text="Optional per-proposal override of the sales person whose name closes out the ``Yours sincerely,`` block. Falls back to the linked project's ``sales_person`` when unset so single-project proposals keep the project's owner by default. Multi-project proposals need the override because different lines may belong to projects with different assigned owners.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals_as_sales_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
