# Generated by Django 6.0.4 on 2026-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposal_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ack_lead_times',
            field=models.BooleanField(default=False, help_text="Customer ticked: 'I understand that manufacturing lead times…'. Required before signing the proposal.", verbose_name='acknowledged lead times'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ack_spec_signing',
            field=models.BooleanField(default=False, help_text="Customer ticked: 'I understand that before label printing, Production Specification Sheets must be signed, and label designs must be reviewed and approved.' Required before signing the proposal.", verbose_name='acknowledged spec sheet signing'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ack_terms',
            field=models.BooleanField(default=False, help_text="Customer ticked: 'I have read the Terms and Conditions which can be found below.' Required before signing the proposal.", verbose_name='acknowledged terms and conditions'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, default=None, help_text='Opaque UUID that grants unauthenticated read-only access to this proposal via the public kiosk URL. When set, the proposal-centric kiosk at ``/p/proposal/<token>`` renders the proposal alongside every attached specification sheet (via ``ProposalLine.specification_sheet``) with a dedicated signature pad per document. The legacy spec-only kiosk at ``/p/<spec_token>`` stays live for sheets shared on their own.', null=True, unique=True, verbose_name='public token'),
        ),
    ]
