# Generated by Django 6.0.4 on 2026-05-12 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('formulations', '0029_formulation_formulations_org_status_idx'),
        ('organizations', '0007_membership_orgs_membership_org_idx'),
        ('proposals', '0007_proposal_ack_lead_times_proposal_ack_spec_signing_and_more'),
        ('specifications', '0012_specificationsheet_specs_formulation_version_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='proposals_org_stat_upd_idx'),
        ),
    ]
