# Generated by Django 6.0.4 on 2026-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_proposal_proposals_org_stat_upd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ack_rd_terms',
            field=models.BooleanField(default=False, help_text="Customer ticked: 'I understand that R&D, sample preparation, flavour development, reformulation, and additional iterations are governed by Vita Manufacture's Research & Development, Sampling and Formulation Terms…' Custom-template proposals only — Ready-to-Go skips it since no R&D phase applies.", verbose_name='acknowledged R&D terms'),
        ),
    ]
