# Generated by Django 6.0.4 on 2026-05-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_clear_legacy_document_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='customer rejected at'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer_rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Optional free-text reason the customer typed when declining via the kiosk. May be empty if they declined without explaining.', verbose_name='customer rejection reason'),
        ),
    ]
