# Generated by Django 6.0.4 on 2026-05-14 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_dynamics_id_customer_dynamics_synced_at_and_more'),
        ('formulations', '0031_formulation_formulations_org_sales_idx'),
        ('organizations', '0011_membership_groups'),
        ('proposals', '0012_proposal_customer_rejected_at_and_more'),
        ('specifications', '0015_specificationsheet_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'sales_person'], name='proposals_org_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'valid_until'], name='proposals_org_valid_idx'),
        ),
    ]
