# Generated by Django 6.0.4 on 2026-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_proposal_proposals_org_sales_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='kiosk_recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Snapshot of the recipient address used the last time the proposal was sent to the client. Drives the portal-activation lookup so a typed override on the compose modal — not just ``Customer.email`` — pins the right portal account.', max_length=254, verbose_name='kiosk recipient email'),
        ),
    ]
