# Generated by Django 6.0.4 on 2026-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_proposal_kiosk_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='activation_code',
            field=models.CharField(blank=True, default='', help_text="Zero-padded 6-digit code printed in the kiosk email body. The portal activation form asks for it after the password step. Cleared once activation succeeds so an attacker who later steals the DB row can't complete a fresh activation against an already-set account.", max_length=6, verbose_name='activation code'),
        ),
    ]
