# Generated by Django 6.0.4 on 2026-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_proposals_pipeline_col_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='activation_code_sent_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp the activation code was last mailed. Codes older than 10 minutes are refused; resends within 60 seconds are refused.', null=True, verbose_name='activation code sent at'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='activation_code',
            field=models.CharField(blank=True, default='', help_text="Zero-padded 6-digit code mailed to the customer when they reach the activation page. Cleared once activation succeeds so an attacker who later steals the DB row can't complete a fresh activation against an already-set account.", max_length=6, verbose_name='activation code'),
        ),
    ]
