# Generated by Django 6.0.4 on 2026-06-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_proposal_activation_code_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Deposit percentage printed in the Custom-template deposit clause (``A deposit of at least X% is required to commence this process``). Scientists set it per quote; defaults to 50 if unspecified. Ignored on the Ready-to-Go template, which has no deposit clause.', max_digits=5, verbose_name='deposit %'),
        ),
    ]
