# Generated by Django 6.0.4 on 2026-08-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0066_alter_formulation_rtg_packaging_options_and_more'),
        ('proposals', '0018_proposal_deposit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalline',
            name='selected_packaging_combo',
            field=models.ForeignKey(blank=True, help_text="RTG-only. The packaging combo the customer picked at order time. PROTECT because deleting a combo that a customer already picked would silently orphan their order's packaging spec. Null on Custom lines (they bind packaging directly via the routing stages).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='formulations.packagingcombo'),
        ),
    ]
