# Generated by Django 6.0.4 on 2026-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_proposalline_selected_packaging_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='brand_key',
            field=models.CharField(choices=[('vita', 'Vita Manufacture'), ('supplement_manufacture_uk', 'Supplement Manufacture UK')], default='vita', help_text="Which brand voice the rendered doc carries. Frozen at creation time; the storefront checkout on the Supplement Manufacture UK web-site sets ``supplement_manufacture_uk`` so downstream renders swap 'Vita Manufacture' for the SMK equivalent. Never rewrite after send — doing so would invalidate the doc hash.", max_length=32, verbose_name='brand'),
        ),
    ]
