# Generated by Django 6.0.4 on 2026-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_proposal_brand_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_reorder',
            field=models.BooleanField(db_index=True, default=False, help_text="True when this proposal was auto-drafted by the portal Reorder flow. Drives the fresh-CO-per-proposal branch in the PSP merge (mirrors RTG's independence rule) and the ``Reorder of <source>`` sub-header on the rendered doc. Never mutated after creation.", verbose_name='is reorder'),
        ),
    ]
