# Generated by Django 6.0.4 on 2026-09-21 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_proposal_is_reorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='additional_sales_people',
            field=models.ManyToManyField(blank=True, help_text="Extra members who contributed to the deal but aren't the assigned owner. Excluded from the primary sales_person FK so the singular 'owner' semantics stay intact.", related_name='proposals_as_additional_sales_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
