# Generated by Django 6.0.4 on 2026-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_proposal_additional_sales_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalline',
            name='tier_margin_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='tier margin overrides'),
        ),
    ]
