# Generated by Django 6.0.4 on 2026-10-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_proposalline_tier_margin_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='previous_rejected_proposal',
            field=models.ForeignKey(blank=True, help_text='If this proposal was created as a retry after a prior proposal was rejected, link back to that rejected row. The detail page renders the previous rejection reason as a banner so sales can address it in this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_proposals', to='proposals.proposal'),
        ),
    ]
