# Generated by Django 6.0.4 on 2026-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_proposal_previous_rejected_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer_rejection_categories',
            field=models.JSONField(blank=True, default=list, help_text="List of category keys the customer ticked on the portal decline form (e.g. ['price', 'lead_time']). Empty on operator-driven rejections; populated by the kiosk path.", verbose_name='customer rejection categories'),
        ),
    ]
