# Generated by Django 6.0.4 on 2026-04-21 09:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('formulations', '0008_formulation_sales_person'),
        ('organizations', '0005_organization_default_spec_limits'),
        ('specifications', '0007_specificationsheet_section_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=120, verbose_name='guest name')),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='guest email')),
                ('guest_session_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the signed kiosk session cookie. Used by the rate-limiter + duplicate-submit guard in the public comment endpoint. Blank for authenticated authors.', max_length=64, verbose_name='guest session hash')),
                ('body', models.TextField(verbose_name='body')),
                ('mentions_cache', models.JSONField(blank=True, default=list, verbose_name='mentions cache')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='The authenticated member who wrote the comment. Null for kiosk guests (commit 6); authoring is still attributed via ``guest_name`` / ``guest_email``.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='formulations.formulation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Root comments have ``parent = NULL``. Replies point at a root comment. Two-level nesting is rejected in ``clean()`` — UI convention matches Asana: flat replies under a single thread.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('specification_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='specifications.specificationsheet')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='comments.comment')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment mention',
                'verbose_name_plural': 'comment mentions',
            },
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply')], max_length=16, verbose_name='kind')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comments.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment notification',
                'verbose_name_plural': 'comment notifications',
            },
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(db_index=True, help_text='The share-link token the session belongs to. Not a FK so rotating the token on the spec sheet does not cascade-delete history — revocation is driven by ``revoked_at``.', verbose_name='public token')),
                ('guest_name', models.CharField(max_length=120, verbose_name='guest name')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='guest email')),
                ('guest_org_label', models.CharField(blank=True, default='', max_length=120, verbose_name='guest organisation label')),
                ('session_hash', models.CharField(max_length=64, unique=True, verbose_name='session hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'kiosk session',
                'verbose_name_plural': 'kiosk sessions',
                'indexes': [models.Index(fields=['public_token', '-last_seen_at'], name='comments_ki_public__a4ec3c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['organization', 'content_type', 'object_id', 'created_at'], name='comments_target_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['formulation', 'is_resolved', 'created_at'], name='comments_formulation_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['specification_sheet', 'is_resolved', 'created_at'], name='comments_spec_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('is_resolved', False), ('parent__isnull', True), _connector='OR'), name='comments_resolve_root_only'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('author__isnull', False), models.Q(models.Q(('guest_name', ''), _negated=True), models.Q(('guest_email', ''), _negated=True)), _connector='OR'), name='comments_identity_required'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='comments_co_mention_27790a_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'mentioned_user'), name='comment_mentions_unique'),
        ),
        migrations.AddIndex(
            model_name='commentnotification',
            index=models.Index(fields=['recipient', '-created_at'], name='comments_co_recipie_6f6090_idx'),
        ),
        migrations.AddIndex(
            model_name='commentnotification',
            index=models.Index(fields=['status'], name='comments_co_status_03ae93_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentnotification',
            constraint=models.UniqueConstraint(fields=('comment', 'recipient', 'kind'), name='comment_notifications_unique'),
        ),
    ]
