# Generated by Django 6.0.4 on 2026-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_org_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='guest organisation label'),
        ),
    ]
