# Generated by Django 6.0.4 on 2026-04-21 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_guest_org_label'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('formulations', '0008_formulation_sales_person'),
        ('organizations', '0005_organization_default_spec_limits'),
        ('specifications', '0007_specificationsheet_section_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='needs_resolution',
            field=models.BooleanField(default=False, verbose_name='needs resolution'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('needs_resolution', False), ('parent__isnull', True), _connector='OR'), name='comments_needs_resolution_root_only'),
        ),
    ]
