# Generated by Django 6.0.4 on 2026-05-18 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_needs_resolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_kind', models.CharField(choices=[('formulation', 'Formulation'), ('specification', 'Specification')], max_length=24, verbose_name='entity kind')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='entity id')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last read at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'thread read state',
                'verbose_name_plural': 'thread read states',
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='thread_read_state_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'entity_kind', 'entity_id'), name='thread_read_state_unique')],
            },
        ),
    ]
