# Generated by Django 6.0.4 on 2026-05-18 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_thread_read_state'),
        ('organizations', '0012_mrpeasy_config'),
        ('specifications', '0016_specificationsheet_specs_fv_kind_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('custom_note', models.TextField(blank=True, default='', verbose_name='custom note')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (cooldown)')], default='queued', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_alerts', to='organizations.organization')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_alerts', to='specifications.specificationsheet')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_alerts_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kiosk alert',
                'verbose_name_plural': 'kiosk alerts',
                'indexes': [models.Index(fields=['sheet', 'recipient_email', '-created_at'], name='kiosk_alerts_sheet_email_idx')],
            },
        ),
    ]
