# Generated by Django 6.0.4 on 2026-05-20 10:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
        ('comments', '0005_kiosk_alert'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('formulations', '0031_formulation_formulations_org_sales_idx'),
        ('organizations', '0013_organization_wix_cff_config'),
        ('specifications', '0016_specificationsheet_specs_fv_kind_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('last_read_at', models.DateTimeField(help_text='Every comment with ``created_at <= last_read_at`` is considered seen by this viewer. The portal / staff UI bumps this on thread-open and on every new message rendered while the tab is foregrounded.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'comment read state',
                'verbose_name_plural': 'comment read states',
            },
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comments_identity_required',
        ),
        migrations.AddField(
            model_name='comment',
            name='client_account',
            field=models.ForeignKey(blank=True, help_text='The portal client who wrote the comment. NULL for staff-authored comments and for legacy kiosk-guest rows. Adding this as a separate FK (rather than a polymorphic GenericFK) keeps the JOIN cheap and the staff comments query unchanged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to='client_portal.clientaccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('shared', 'Shared')], db_index=True, default='internal', help_text="``internal`` is staff-only; ``shared`` is visible to both the staff team and the portal client whose customer this comment's target belongs to.", max_length=16, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The authenticated staff member who wrote the comment. Null for kiosk guests (legacy) and for portal client authors (see ``client_account``).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('author__isnull', False), ('client_account__isnull', False), models.Q(models.Q(('guest_name', ''), _negated=True), models.Q(('guest_email', ''), _negated=True)), _connector='OR'), name='comments_identity_required'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('author__isnull', True), ('client_account__isnull', True), _connector='OR'), name='comments_identity_single_path'),
        ),
        migrations.AddField(
            model_name='commentreadstate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='commentreadstate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_states', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='commentreadstate',
            name='viewer_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_states', to='client_portal.clientaccount'),
        ),
        migrations.AddField(
            model_name='commentreadstate',
            name='viewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentreadstate',
            index=models.Index(fields=['viewer_user', 'content_type', 'object_id'], name='crs_user_target_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreadstate',
            index=models.Index(fields=['viewer_client', 'content_type', 'object_id'], name='crs_client_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreadstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('viewer_user__isnull', False), ('viewer_client__isnull', True)), models.Q(('viewer_user__isnull', True), ('viewer_client__isnull', False)), _connector='OR'), name='crs_one_viewer'),
        ),
        migrations.AddConstraint(
            model_name='commentreadstate',
            constraint=models.UniqueConstraint(condition=models.Q(('viewer_user__isnull', False)), fields=('viewer_user', 'content_type', 'object_id'), name='crs_unique_user_target'),
        ),
        migrations.AddConstraint(
            model_name='commentreadstate',
            constraint=models.UniqueConstraint(condition=models.Q(('viewer_client__isnull', False)), fields=('viewer_client', 'content_type', 'object_id'), name='crs_unique_client_target'),
        ),
    ]
