# Generated by Django 6.0.4 on 2026-05-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_commentreadstate_and_more'),
        ('proposals', '0015_proposal_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposal'),
        ),
    ]
