# Generated by Django 6.0.4 on 2026-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadreadstate',
            name='entity_kind',
            field=models.CharField(choices=[('formulation', 'Formulation'), ('specification', 'Specification'), ('proposal', 'Proposal')], max_length=24, verbose_name='entity kind'),
        ),
    ]
