# Generated by Django 6.0.4 on 2026-05-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cff_submissions', '0001_initial'),
        ('comments', '0008_alter_threadreadstate_entity_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cff_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cff_submissions.cffsubmission'),
        ),
        migrations.AlterField(
            model_name='threadreadstate',
            name='entity_kind',
            field=models.CharField(choices=[('formulation', 'Formulation'), ('specification', 'Specification'), ('proposal', 'Proposal'), ('cff_submission', 'CFF Submission')], max_length=24, verbose_name='entity kind'),
        ),
    ]
