# Generated by Django 6.0.4 on 2026-05-26 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_comment_cff_submission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='threadreadstate',
            name='thread_read_state_unique',
        ),
        migrations.AddField(
            model_name='threadreadstate',
            name='visibility',
            field=models.CharField(blank=True, choices=[('', 'Any (legacy)'), ('internal', 'Internal'), ('shared', 'Shared')], db_index=True, default='', max_length=16, verbose_name='visibility lane'),
        ),
        migrations.AddConstraint(
            model_name='threadreadstate',
            constraint=models.UniqueConstraint(fields=('user', 'entity_kind', 'entity_id', 'visibility'), name='thread_read_state_unique'),
        ),
    ]
