# Generated by Django 6.0.4 on 2026-05-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_remove_threadreadstate_thread_read_state_unique_and_more'),
        ('label_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='label_design.labeldesign'),
        ),
        migrations.AlterField(
            model_name='threadreadstate',
            name='entity_kind',
            field=models.CharField(choices=[('formulation', 'Formulation'), ('specification', 'Specification'), ('proposal', 'Proposal'), ('cff_submission', 'CFF Submission'), ('label_design', 'Label design')], max_length=24, verbose_name='entity kind'),
        ),
    ]
