# Generated by Django 6.0.4 on 2026-05-29 08:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_comment_label_design_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to='comments.comment')),
            ],
            options={
                'verbose_name': 'client comment notification',
                'verbose_name_plural': 'client comment notifications',
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='comments_cl_recipie_aa1fa6_idx'), models.Index(fields=['status'], name='comments_cl_status_7cdfc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment', 'recipient_email'), name='client_comment_notifications_unique')],
            },
        ),
    ]
