# Generated by Django 6.0.4 on 2026-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_clientcommentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnotification',
            name='kind',
            field=models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('customer_post', 'Customer post')], max_length=16, verbose_name='kind'),
        ),
    ]
