# Generated by Django 6.0.4 on 2026-05-27 11:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0033_formulation_formulations_org_lead_sci_idx'),
        ('label_design', '0001_initial'),
        ('organizations', '0014_backfill_proposals_view_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='GBP', max_length=3, verbose_name='currency')),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank_transfer', max_length=24, verbose_name='method')),
                ('external_reference', models.CharField(blank=True, default='', help_text='Bank ref, Stripe payment intent id, etc. — whatever the finance team needs to reconcile against the external ledger.', max_length=160, verbose_name='external reference')),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='invoice number')),
                ('paid_at', models.DateTimeField(verbose_name='paid at')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('voided', 'Voided')], default='pending', max_length=16, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(help_text='PROTECT because a project that received a payment cannot be silently deleted — finance audit relies on the linkage.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='formulations.formulation')),
                ('label_design', models.ForeignKey(blank=True, help_text='The downstream label-design workflow this payment unlocks. SET_NULL so the payment record survives if the label workflow is ever deleted (which should be rare — kept conservative for the audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='label_design.labeldesign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('-paid_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='payments_pa_organiz_1d83a8_idx'), models.Index(fields=['formulation', '-paid_at'], name='payments_pa_formula_32d046_idx')],
            },
        ),
    ]
