# Generated by Django 6.0.4 on 2026-05-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='assigned_finance_officer',
            field=models.ForeignKey(blank=True, help_text='Finance-team member who owns this payment (recording, chasing, reconciliation). Pointer-only — being assigned grants no capabilities. Gated by the ``finance.assign_officer`` capability. Mirrors the ``sales_person`` / ``lead_scientist`` pointer convention and drives the ``scope=mine`` filter on the finance queue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
