# Generated by Django 6.0.4 on 2026-08-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_design', '0005_collapse_label_designs_per_formulation'),
        ('payments', '0003_payment_kind_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('final', 'Final')], db_index=True, default='final', help_text='Which gate this payment opens — DEPOSIT (unlocks trial batches, per-proposal) or FINAL (unlocks label design, per-formulation). Existing rows pre-migration were all the label-gate variant so the default keeps them intact.', max_length=16, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='label_design',
            field=models.ForeignKey(blank=True, help_text='FINAL payments only — the downstream label-design workflow this payment unlocks. SET_NULL so the payment record survives if the label workflow is ever deleted (which should be rare — kept conservative for the audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='label_design.labeldesign'),
        ),
    ]
