# Generated by Django 6.0.4 on 2026-08-01 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_kind_alter_payment_label_design'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='payment-invoices/', verbose_name='file')),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=120)),
                ('byte_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.payment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment file',
                'verbose_name_plural': 'payment files',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['payment', '-uploaded_at'], name='payments_pa_payment_187876_idx')],
            },
        ),
    ]
