# Generated by Django 6.0.4 on 2026-08-10 06:13

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_customer(apps, schema_editor):
    """Populate ``Payment.customer`` from existing linkage.

    FINAL rows have a formulation FK; use ``formulation.customer_id``.
    DEPOSIT rows have a proposal FK; use ``proposal.customer_id``.
    Rows that resolve to neither stay null — the SET_NULL default is
    the correct "unknown customer" state for imported / hand-crafted
    rows that predate the storefront checkout flow.
    """
    Payment = apps.get_model("payments", "Payment")
    updates = []
    for row in Payment.objects.select_related(
        "formulation", "proposal"
    ).only("id", "formulation__customer_id", "proposal__customer_id"):
        customer_id = None
        if row.formulation_id is not None:
            customer_id = getattr(row.formulation, "customer_id", None)
        if customer_id is None and row.proposal_id is not None:
            customer_id = getattr(row.proposal, "customer_id", None)
        if customer_id is not None:
            row.customer_id = customer_id
            updates.append(row)
    if updates:
        Payment.objects.bulk_update(updates, ["customer_id"], batch_size=500)


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — the FK column is dropped by the schema
    op, so wiping values before that is redundant.
    """
    return


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_unique_email_per_org'),
        ('payments', '0005_paymentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="Address-book customer the payment is billed to. Denormalized alongside the formulation / proposal FKs so the finance queue can surface 'who ordered this' without walking two joins per row. Backfilled from ``formulation.customer`` (FINAL) / ``proposal.customer`` (DEPOSIT) at migration time; new rows get it set at ``record_payment`` time. SET_NULL keeps the audit trail intact when a customer row is archived.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer'),
        ),
        migrations.RunPython(backfill_payment_customer, noop_reverse),
    ]
