# Generated by Django 6.0.4 on 2026-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_sample_allocation_deposit_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('final', 'Final'), ('additional_samples', 'Additional samples')], db_index=True, default='final', help_text='Which gate this payment opens — DEPOSIT (unlocks trial batches, per-proposal) or FINAL (unlocks label design, per-formulation). Existing rows pre-migration were all the label-gate variant so the default keeps them intact.', max_length=32, verbose_name='kind'),
        ),
    ]
