# Generated by Django 6.0.4 on 2026-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepricingconfig',
            name='label_design_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='label-design fee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('final', 'Final'), ('additional_samples', 'Additional samples'), ('label_design', 'Label design')], db_index=True, default='final', help_text='Which gate this payment opens — DEPOSIT (unlocks trial batches, per-proposal) or FINAL (unlocks label design, per-formulation). Existing rows pre-migration were all the label-gate variant so the default keeps them intact.', max_length=32, verbose_name='kind'),
        ),
    ]
