# Generated by Django 6.0.4 on 2026-04-15 16:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Machine identifier. Snake_case, never renamed after creation.', max_length=64, verbose_name='key')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('single_select', 'Single select'), ('multi_select', 'Multi select')], max_length=32, verbose_name='data type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('options', models.JSONField(blank=True, default=list, help_text='Ordered list of {value, label} pairs for select types.', verbose_name='options')),
                ('display_order', models.IntegerField(default=0, verbose_name='display order')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'attribute definition',
                'verbose_name_plural': 'attribute definitions',
                'ordering': ('display_order', 'label'),
            },
        ),
    ]
