# Generated by Django 6.0.4 on 2026-04-15 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('catalogues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='catalogues.catalogue'),
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attribute_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_attribute_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attributedefinition',
            index=models.Index(fields=['catalogue', 'is_archived'], name='attributes__catalog_c7eb24_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributedefinition',
            constraint=models.UniqueConstraint(fields=('catalogue', 'key'), name='attributes_definition_unique_key_per_catalogue'),
        ),
    ]
