# Generated by Django 6.0.4 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_seed_powder_water_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Optional help text rendered under the input on the item edit form. Use it to explain non-obvious semantics -- e.g. a single rate field whose unit is interpreted differently depending on the item's ``use_as`` band.", verbose_name='description'),
        ),
    ]
